In [23]:
import pandas as pd

df = pd.read_excel('../Example_database_withoutrois.xlsx') 
df.head()

,Identifiers,age,sex,education,education_group,language,fluency_score,handedness,nb_language,hearing,...,anxiety_score,smoking,alcohol,poly_pharm5,poly_pharm10,physical_activity,social_life,cognitive_activities,nutrition_score,sleep_deprivation
0,4509950,70.3,1.0,21.0,4.0,1.0,18.0,0.0,2,0.0,...,6.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,7424803,78.4,1.0,14.0,2.0,1.0,19.0,0.0,2,1.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,7874568,74.5,0.0,18.0,4.0,1.0,17.0,0.0,2,0.0,...,3.0,0.0,0.0,NaN,NaN,0.0,1.0,0.0,0.0,1.0
3,3865361,73.3,1.0,14.0,2.0,1.0,17.0,0.0,2,0.0,...,4.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,6841569,73.8,1.0,15.0,3.0,1.0,24.0,0.0,1,0.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0

From this function we can see that we have null values in some columns, and since we are in the exploratory phase we need clean and complete data, in order to understand relationships between columns, so now we gonna drop Na values

In [24]:
# List of column names you want to keep
basic_columns = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'risk_handicap']
all_columns = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'handedness','nb_language','hearing','moca','ravlt_imm','ravlt_delay', 'logic_imm', 'logic_delay', 'risk_handicap']
all_columns_plus_plus = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'handedness','nb_language','hearing','moca','ravlt_imm','ravlt_delay', 'logic_imm', 'logic_delay', 'hist_demence_fam', 'hist_demence_parent', 'living_alone', 'income', 'retired','stroke', 'tbi', 'hta', 'diab_type2', 'obesity', 'depression', 'anxiety', 'smoking', 'alcohol','poly_pharm5', 'physical_activity', 'social_life','cognitive_activities','nutrition_score','sleep_deprivation', 'risk_handicap']

# Select only those columns
df_basic = df[basic_columns]
df_all = df[all_columns]
df_all_plus_plus = df[all_columns_plus_plus]

In [25]:
df_basic = df_basic.dropna()
df_all = df_all.dropna()
df_all_plus_plus = df_all_plus_plus.dropna()


df_basic.describe()
df_all.describe()
df_all_plus_plus.describe()

,age,sex,education,language,fluency_score,neurocog_age_flu_weight,handedness,nb_language,hearing,moca,...,anxiety,smoking,alcohol,poly_pharm5,physical_activity,social_life,cognitive_activities,nutrition_score,sleep_deprivation,risk_handicap
count,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,...,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000
mean,72.095808,0.543413,15.619012,0.185629,18.995509,74.731080,0.104790,1.959581,0.040419,23.869760,...,0.059880,0.426647,0.115269,0.630240,0.103293,0.464072,0.100299,0.368263,0.113772,0.151198
std,6.695071,0.498485,3.442239,0.389098,6.296638,11.202246,0.306513,1.051813,0.197088,4.258807,...,0.237443,0.494961,0.319586,0.483101,0.304570,0.499081,0.300624,0.482695,0.317773,0.305445
min,57.400000,0.000000,5.000000,0.000000,0.000000,48.941804,0.000000,1.000000,0.000000,9.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,66.600000,0.000000,13.000000,0.000000,15.000000,66.374971,0.000000,1.000000,0.000000,21.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,72.250000,1.000000,15.250000,0.000000,19.000000,74.357982,0.000000,2.000000,0.000000,25.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,77.000000,1.000000,18.000000,0.000000,23.000000,82.964218,0.000000,2.000000,0.000000,27.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,89.700000,1.000000,30.000000,1.000000,37.000000,104.935177,1.000000,6.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

We can see that we droped the half of our data, in fact that will impact the performance of our models, but in a first place to get to know the correlations and the right columns to choose this is the only way. Once this is done we can get back to drop non necessary columns and use only target columns with no null values

In [26]:
df_basic = df_basic.drop('Identifiers', axis=1)
df_all = df_all.drop('Identifiers', axis=1)
df_all_plus_plus = df_all_plus_plus.drop('Identifiers', axis=1)

In [27]:
corr_all = df_all.corr()
corr_basic = df_basic.corr()
corr_all_plus_plus = df_all_plus_plus.corr()

In [28]:
correlation_all = pd.DataFrame(corr_all)
correlation_basic = pd.DataFrame(corr_basic)
correlation_all_plus_plus = pd.DataFrame(corr_all_plus_plus)

In [29]:
new_correlation_all = abs(correlation_all['risk_handicap'])
new_correlation_basic = abs(correlation_basic['risk_handicap'])
new_correlation_all_plus_plus = abs(correlation_all_plus_plus['risk_handicap'])

In [30]:
new_correlation_all_plus_plus = new_correlation_all_plus_plus.sort_values(ascending=False)
new_correlation_all_plus_plus

risk_handicap              1.000000
moca                       0.592799
ravlt_imm                  0.544711
neurocog_age_flu_weight    0.517676
ravlt_delay                0.478157
fluency_score              0.475159
logic_imm                  0.435578
logic_delay                0.430133
living_alone               0.129275
language                   0.122976
age                        0.121278
sex                        0.107178
cognitive_activities       0.095838
poly_pharm5                0.074635
alcohol                    0.071298
handedness                 0.062712
hta                        0.057448
education                  0.057423
physical_activity          0.055320
retired                    0.052936
sleep_deprivation          0.046200
smoking                    0.035614
hearing                    0.035306
anxiety                    0.031998
diab_type2                 0.029338
stroke                     0.025125
income                     0.019063
tbi                        0.015502
obesity                    0.014598
hist_demence_fam           0.012905
nutrition_score            0.007063
nb_language                0.005051
depression                 0.002812
hist_demence_parent        0.002424
social_life                0.001266
Name: risk_handicap, dtype: float64

In [31]:
new_correlation_basic = new_correlation_basic.sort_values(ascending=False)
new_correlation_basic

risk_handicap              1.000000
neurocog_age_flu_weight    0.532304
fluency_score              0.492299
sex                        0.146414
language                   0.141159
age                        0.123385
education                  0.063340
Name: risk_handicap, dtype: float64

In [32]:
new_correlation_all = new_correlation_all.sort_values(ascending=False)
new_correlation_all

risk_handicap              1.000000
moca                       0.582799
ravlt_imm                  0.541008
neurocog_age_flu_weight    0.534293
ravlt_delay                0.495139
fluency_score              0.462223
logic_imm                  0.451912
logic_delay                0.448326
language                   0.153166
age                        0.148917
sex                        0.114979
education                  0.054646
handedness                 0.049446
hearing                    0.041225
nb_language                0.024893
Name: risk_handicap, dtype: float64

In [33]:
new_correlation_all_plus_plus = pd.DataFrame(new_correlation_all_plus_plus)
new_correlation_all_plus_plus['column_name'] = new_correlation_all_plus_plus.index
new_correlation_all_plus_plus.reset_index(drop=True, inplace=True)

In [34]:
new_correlation_basic = pd.DataFrame(new_correlation_basic)
new_correlation_basic['column_name'] = new_correlation_basic.index
new_correlation_basic.reset_index(drop=True, inplace=True)

In [35]:
new_correlation_all = pd.DataFrame(new_correlation_all)
new_correlation_all['column_name'] = new_correlation_all.index
new_correlation_all.reset_index(drop=True, inplace=True)

In [36]:
relevant_columns_basic = new_correlation_basic.loc[new_correlation_basic['risk_handicap'] > 0, 'column_name']
relevant_columns_basic = relevant_columns_basic[relevant_columns_basic != 'risk_handicap']
relevant_columns_basic = relevant_columns_basic[relevant_columns_basic != 'risk_handicap']
print(relevant_columns_basic)


relevant_columns_all = new_correlation_all.loc[new_correlation_all['risk_handicap'] > 0, 'column_name']
relevant_columns_all = relevant_columns_all[relevant_columns_all != 'risk_handicap']
relevant_columns_all = relevant_columns_all[relevant_columns_all != 'risk_handicap']
print(relevant_columns_all)


relevant_columns_all_plus_plus = new_correlation_all_plus_plus.loc[new_correlation_all_plus_plus['risk_handicap'] > 0, 'column_name']
relevant_columns_all_plus_plus = relevant_columns_all_plus_plus[relevant_columns_all_plus_plus != 'risk_handicap']
relevant_columns_all_plus_plus = relevant_columns_all_plus_plus[relevant_columns_all_plus_plus != 'risk_handicap']
print(relevant_columns_all_plus_plus)

1    neurocog_age_flu_weight
2              fluency_score
3                        sex
4                   language
5                        age
6                  education
Name: column_name, dtype: object
1                        moca
2                   ravlt_imm
3     neurocog_age_flu_weight
4                 ravlt_delay
5               fluency_score
6                   logic_imm
7                 logic_delay
8                    language
9                         age
10                        sex
11                  education
12                 handedness
13                    hearing
14                nb_language
Name: column_name, dtype: object
1                        moca
2                   ravlt_imm
3     neurocog_age_flu_weight
4                 ravlt_delay
5               fluency_score
6                   logic_imm
7                 logic_delay
8                living_alone
9                    language
10                        age
11                        sex
12       cognitive_activities
13                poly_pharm5
14                    alcohol
15                 handedness
16                        hta
17                  education
18          physical_activity
19                    retired
20          sleep_deprivation
21                    smoking
22                    hearing
23                    anxiety
24                 diab_type2
25                     stroke
26                     income
27                        tbi
28                    obesity
29           hist_demence_fam
30            nutrition_score
31                nb_language
32                 depression
33        hist_demence_parent
34                social_life
Name: column_name, dtype: object

In this part we will choose the relevent columns for our model, these columns should have a correlation value higher than 50%

In [37]:
from sklearn.metrics import median_absolute_error, mean_absolute_error, mean_squared_error
import numpy as np
def print_error_metrics(y_true: np.array, y_pred: np.array) -> None:
    """
    Function to compute the mean absolute error, mean squared error, and median absolute error and print to screen
    
    Inputs:
        y_true -> array containing actual dependant variable
        y_pred -> array containing model predictions
    """
    mee = median_absolute_error(y_true,y_pred)
    mae = mean_absolute_error(y_true,y_pred)
    mse = mean_squared_error(y_true,y_pred)
    print("The median absolute error is: {:.2f}".format(mee))
    print("The mean absolute error is: {:.2f}".format(mae))
    print("The root mean squared error is: {:.2f}".format(np.sqrt(mse)))

In [38]:
def pred_to_proba(y_pred):
    predictions = []
    for value in y_pred:
        value = int(value*100)
        if value < 0 :
            value = 0
        elif value > 100 :
            value = 100
        else:
            pass
        predictions.append(value/100)
    
    return predictions

In [39]:
#!pip install lightgbm==3.3.5

In [40]:
#pip install xgboost

In [41]:
#!pip install catboost

In [42]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor 
import catboost as cb

def train_best_reg_models(df, relevant_columns):
    X_train, X_test, y_train, y_test = train_test_split(df[relevant_columns],df["risk_handicap"],test_size=0.8)
    XGB_reg = XGBRegressor().fit(X_train, y_train)
    y_predict = pred_to_proba(XGB_reg.predict(X_test))
    print("Error metrics for XGBoost regression model :")
    print_error_metrics(y_test, y_predict)

    LGBM_reg = LGBMRegressor(metric='rmse')
    LGBM_reg.fit(X_train, y_train)
    y_predict = pred_to_proba(LGBM_reg.predict(X_test))
    print("Error metrics for LightGBM regression model :")
    print_error_metrics(y_test, y_predict)

    model_CB = cb.CatBoostRegressor()
    model_CB.fit(X_train, y_train)
    y_predict = pred_to_proba(model_CB.predict(X_test))
    print("Error metrics for Cat boost regression model :")
    print_error_metrics(y_test, y_predict)
    return XGB_reg, LGBM_reg, model_CB

In [43]:
XGB_reg_basic, LGBM_reg_basic, model_CB_basic = train_best_reg_models(df_basic, relevant_columns_basic)

Error metrics for XGBoost regression model :
The median absolute error is: 0.00
The mean absolute error is: 0.13
The root mean squared error is: 0.24
Error metrics for LightGBM regression model :
The median absolute error is: 0.04
The mean absolute error is: 0.13
The root mean squared error is: 0.22
Learning rate set to 0.032044
0:	learn: 0.3243968	total: 155ms	remaining: 2m 34s
1:	learn: 0.3216016	total: 156ms	remaining: 1m 17s
2:	learn: 0.3189375	total: 156ms	remaining: 52s
3:	learn: 0.3166570	total: 157ms	remaining: 39.2s
4:	learn: 0.3135638	total: 158ms	remaining: 31.4s
5:	learn: 0.3105973	total: 159ms	remaining: 26.3s
6:	learn: 0.3080547	total: 160ms	remaining: 22.6s
7:	learn: 0.3050304	total: 160ms	remaining: 19.9s
8:	learn: 0.3013169	total: 161ms	remaining: 17.8s
9:	learn: 0.2985628	total: 162ms	remaining: 16s
10:	learn: 0.2957782	total: 163ms	remaining: 14.6s
11:	learn: 0.2933952	total: 163ms	remaining: 13.4s
12:	learn: 0.2911055	total: 164ms	remaining: 12.5s
13:	learn: 0.2874806	total: 165ms	remaining: 11.6s
14:	learn: 0.2855626	total: 166ms	remaining: 10.9s
15:	learn: 0.2832705	total: 166ms	remaining: 10.2s
16:	learn: 0.2810639	total: 167ms	remaining: 9.66s
17:	learn: 0.2789732	total: 168ms	remaining: 9.15s
18:	learn: 0.2770071	total: 169ms	remaining: 8.71s
19:	learn: 0.2747806	total: 170ms	remaining: 8.32s
20:	learn: 0.2731487	total: 171ms	remaining: 7.95s
21:	learn: 0.2713516	total: 171ms	remaining: 7.61s
22:	learn: 0.2686587	total: 172ms	remaining: 7.3s
23:	learn: 0.2666267	total: 172ms	remaining: 7.01s
24:	learn: 0.2643408	total: 173ms	remaining: 6.75s
25:	learn: 0.2629766	total: 173ms	remaining: 6.5s
26:	learn: 0.2612646	total: 174ms	remaining: 6.27s
27:	learn: 0.2596459	total: 175ms	remaining: 6.06s
28:	learn: 0.2570185	total: 175ms	remaining: 5.86s
29:	learn: 0.2555573	total: 176ms	remaining: 5.68s
30:	learn: 0.2532692	total: 176ms	remaining: 5.5s
31:	learn: 0.2514863	total: 177ms	remaining: 5.34s
32:	learn: 0.2497291	total: 177ms	remaining: 5.19s
33:	learn: 0.2475705	total: 178ms	remaining: 5.05s
34:	learn: 0.2459558	total: 178ms	remaining: 4.92s
35:	learn: 0.2447375	total: 179ms	remaining: 4.79s
36:	learn: 0.2435086	total: 179ms	remaining: 4.67s
37:	learn: 0.2423254	total: 180ms	remaining: 4.55s
38:	learn: 0.2398140	total: 180ms	remaining: 4.45s
39:	learn: 0.2382879	total: 181ms	remaining: 4.34s
40:	learn: 0.2367456	total: 182ms	remaining: 4.25s
41:	learn: 0.2349711	total: 182ms	remaining: 4.16s
42:	learn: 0.2337577	total: 183ms	remaining: 4.08s
43:	learn: 0.2321218	total: 184ms	remaining: 4s
44:	learn: 0.2301329	total: 185ms	remaining: 3.92s
45:	learn: 0.2293275	total: 185ms	remaining: 3.83s
46:	learn: 0.2279819	total: 185ms	remaining: 3.76s
47:	learn: 0.2270171	total: 186ms	remaining: 3.69s
48:	learn: 0.2256672	total: 187ms	remaining: 3.62s
49:	learn: 0.2241545	total: 187ms	remaining: 3.56s
50:	learn: 0.2226427	total: 188ms	remaining: 3.5s
51:	learn: 0.2215331	total: 189ms	remaining: 3.44s
52:	learn: 0.2206790	total: 189ms	remaining: 3.38s
53:	learn: 0.2194287	total: 190ms	remaining: 3.33s
54:	learn: 0.2180627	total: 191ms	remaining: 3.27s
55:	learn: 0.2164499	total: 191ms	remaining: 3.22s
56:	learn: 0.2150675	total: 192ms	remaining: 3.17s
57:	learn: 0.2137443	total: 192ms	remaining: 3.12s
58:	learn: 0.2117068	total: 193ms	remaining: 3.08s
59:	learn: 0.2101161	total: 193ms	remaining: 3.03s
60:	learn: 0.2090575	total: 194ms	remaining: 2.99s
61:	learn: 0.2079490	total: 195ms	remaining: 2.94s
62:	learn: 0.2070332	total: 195ms	remaining: 2.9s
63:	learn: 0.2059479	total: 196ms	remaining: 2.87s
64:	learn: 0.2044905	total: 197ms	remaining: 2.83s
65:	learn: 0.2036265	total: 197ms	remaining: 2.79s
66:	learn: 0.2027949	total: 198ms	remaining: 2.76s
67:	learn: 0.2018206	total: 199ms	remaining: 2.73s
68:	learn: 0.2008782	total: 199ms	remaining: 2.69s
69:	learn: 0.2000472	total: 200ms	remaining: 2.66s
70:	learn: 0.1989770	total: 201ms	remaining: 2.62s
71:	learn: 0.1983048	total: 201ms	remaining: 2.59s
72:	learn: 0.1976366	total: 202ms	remaining: 2.56s
73:	learn: 0.1968481	total: 202ms	remaining: 2.53s
74:	learn: 0.1961260	total: 203ms	remaining: 2.5s
75:	learn: 0.1948372	total: 203ms	remaining: 2.47s
76:	learn: 0.1941295	total: 204ms	remaining: 2.45s
77:	learn: 0.1934086	total: 205ms	remaining: 2.42s
78:	learn: 0.1921707	total: 205ms	remaining: 2.39s
79:	learn: 0.1904876	total: 206ms	remaining: 2.37s
80:	learn: 0.1897721	total: 207ms	remaining: 2.34s
81:	learn: 0.1889625	total: 207ms	remaining: 2.32s
82:	learn: 0.1878647	total: 208ms	remaining: 2.3s
83:	learn: 0.1871455	total: 209ms	remaining: 2.27s
84:	learn: 0.1866268	total: 209ms	remaining: 2.25s
85:	learn: 0.1856956	total: 210ms	remaining: 2.23s
86:	learn: 0.1850275	total: 210ms	remaining: 2.21s
87:	learn: 0.1840091	total: 211ms	remaining: 2.19s
88:	learn: 0.1831509	total: 212ms	remaining: 2.17s
89:	learn: 0.1823835	total: 213ms	remaining: 2.15s
90:	learn: 0.1816078	total: 214ms	remaining: 2.13s
91:	learn: 0.1808905	total: 215ms	remaining: 2.12s
92:	learn: 0.1802238	total: 215ms	remaining: 2.1s
93:	learn: 0.1796922	total: 216ms	remaining: 2.08s
94:	learn: 0.1792848	total: 217ms	remaining: 2.07s
95:	learn: 0.1789265	total: 218ms	remaining: 2.05s
96:	learn: 0.1784176	total: 218ms	remaining: 2.03s
97:	learn: 0.1779505	total: 219ms	remaining: 2.01s
98:	learn: 0.1772196	total: 219ms	remaining: 2s
99:	learn: 0.1762842	total: 220ms	remaining: 1.98s
100:	learn: 0.1759680	total: 221ms	remaining: 1.96s
101:	learn: 0.1756373	total: 221ms	remaining: 1.95s
102:	learn: 0.1750413	total: 222ms	remaining: 1.93s
103:	learn: 0.1745425	total: 222ms	remaining: 1.92s
104:	learn: 0.1741553	total: 223ms	remaining: 1.9s
105:	learn: 0.1732010	total: 224ms	remaining: 1.89s
106:	learn: 0.1725986	total: 224ms	remaining: 1.87s
107:	learn: 0.1723238	total: 225ms	remaining: 1.86s
108:	learn: 0.1718657	total: 225ms	remaining: 1.84s
109:	learn: 0.1711332	total: 226ms	remaining: 1.83s
110:	learn: 0.1700009	total: 227ms	remaining: 1.81s
111:	learn: 0.1692570	total: 227ms	remaining: 1.8s
112:	learn: 0.1687135	total: 228ms	remaining: 1.79s
113:	learn: 0.1680605	total: 229ms	remaining: 1.78s
114:	learn: 0.1674904	total: 230ms	remaining: 1.77s
115:	learn: 0.1668791	total: 230ms	remaining: 1.75s
116:	learn: 0.1665523	total: 231ms	remaining: 1.74s
117:	learn: 0.1662777	total: 231ms	remaining: 1.73s
118:	learn: 0.1653874	total: 232ms	remaining: 1.72s
119:	learn: 0.1651651	total: 233ms	remaining: 1.71s
120:	learn: 0.1646139	total: 233ms	remaining: 1.69s
121:	learn: 0.1640348	total: 234ms	remaining: 1.68s
122:	learn: 0.1633508	total: 234ms	remaining: 1.67s
123:	learn: 0.1630628	total: 235ms	remaining: 1.66s
124:	learn: 0.1622214	total: 236ms	remaining: 1.65s
125:	learn: 0.1617911	total: 236ms	remaining: 1.64s
126:	learn: 0.1613554	total: 237ms	remaining: 1.63s
127:	learn: 0.1608808	total: 238ms	remaining: 1.62s
128:	learn: 0.1601221	total: 238ms	remaining: 1.61s
129:	learn: 0.1600883	total: 238ms	remaining: 1.59s
130:	learn: 0.1594377	total: 239ms	remaining: 1.59s
131:	learn: 0.1588849	total: 240ms	remaining: 1.58s
132:	learn: 0.1584076	total: 240ms	remaining: 1.57s
133:	learn: 0.1576262	total: 241ms	remaining: 1.56s
134:	learn: 0.1572393	total: 242ms	remaining: 1.55s
135:	learn: 0.1568317	total: 243ms	remaining: 1.54s
136:	learn: 0.1561093	total: 243ms	remaining: 1.53s
137:	learn: 0.1555343	total: 244ms	remaining: 1.52s
138:	learn: 0.1549671	total: 244ms	remaining: 1.51s
139:	learn: 0.1544141	total: 245ms	remaining: 1.5s
140:	learn: 0.1533278	total: 245ms	remaining: 1.5s
141:	learn: 0.1528149	total: 246ms	remaining: 1.49s
142:	learn: 0.1522789	total: 247ms	remaining: 1.48s
143:	learn: 0.1518124	total: 247ms	remaining: 1.47s
144:	learn: 0.1510066	total: 248ms	remaining: 1.46s
145:	learn: 0.1504223	total: 248ms	remaining: 1.45s
146:	learn: 0.1502363	total: 249ms	remaining: 1.44s
147:	learn: 0.1500204	total: 249ms	remaining: 1.44s
148:	learn: 0.1496434	total: 250ms	remaining: 1.43s
149:	learn: 0.1493754	total: 251ms	remaining: 1.42s
150:	learn: 0.1491497	total: 252ms	remaining: 1.41s
151:	learn: 0.1484474	total: 252ms	remaining: 1.41s
152:	learn: 0.1477073	total: 253ms	remaining: 1.4s
153:	learn: 0.1470000	total: 253ms	remaining: 1.39s
154:	learn: 0.1464826	total: 254ms	remaining: 1.38s
155:	learn: 0.1461010	total: 254ms	remaining: 1.38s
156:	learn: 0.1454591	total: 255ms	remaining: 1.37s
157:	learn: 0.1449117	total: 256ms	remaining: 1.36s
158:	learn: 0.1448191	total: 256ms	remaining: 1.35s
159:	learn: 0.1442076	total: 258ms	remaining: 1.35s
160:	learn: 0.1437452	total: 258ms	remaining: 1.35s
161:	learn: 0.1435531	total: 259ms	remaining: 1.34s
162:	learn: 0.1426431	total: 259ms	remaining: 1.33s
163:	learn: 0.1422642	total: 260ms	remaining: 1.32s
164:	learn: 0.1418022	total: 261ms	remaining: 1.32s
165:	learn: 0.1410822	total: 261ms	remaining: 1.31s
166:	learn: 0.1409284	total: 262ms	remaining: 1.31s
167:	learn: 0.1404894	total: 263ms	remaining: 1.3s
168:	learn: 0.1401245	total: 263ms	remaining: 1.29s
169:	learn: 0.1397661	total: 264ms	remaining: 1.29s
170:	learn: 0.1396265	total: 264ms	remaining: 1.28s
171:	learn: 0.1392634	total: 265ms	remaining: 1.27s
172:	learn: 0.1390713	total: 265ms	remaining: 1.27s
173:	learn: 0.1385918	total: 266ms	remaining: 1.26s
174:	learn: 0.1378041	total: 267ms	remaining: 1.26s
175:	learn: 0.1371635	total: 267ms	remaining: 1.25s
176:	learn: 0.1368605	total: 268ms	remaining: 1.25s
177:	learn: 0.1362858	total: 269ms	remaining: 1.24s
178:	learn: 0.1361632	total: 269ms	remaining: 1.23s
179:	learn: 0.1358925	total: 270ms	remaining: 1.23s
180:	learn: 0.1355108	total: 270ms	remaining: 1.22s
181:	learn: 0.1349839	total: 271ms	remaining: 1.22s
182:	learn: 0.1346254	total: 272ms	remaining: 1.21s
183:	learn: 0.1339835	total: 272ms	remaining: 1.21s
184:	learn: 0.1336254	total: 273ms	remaining: 1.2s
185:	learn: 0.1334368	total: 274ms	remaining: 1.2s
186:	learn: 0.1331904	total: 274ms	remaining: 1.19s
187:	learn: 0.1328399	total: 275ms	remaining: 1.19s
188:	learn: 0.1324414	total: 275ms	remaining: 1.18s
189:	learn: 0.1322873	total: 276ms	remaining: 1.18s
190:	learn: 0.1317072	total: 276ms	remaining: 1.17s
191:	learn: 0.1314204	total: 277ms	remaining: 1.17s
192:	learn: 0.1313028	total: 278ms	remaining: 1.16s
193:	learn: 0.1309793	total: 278ms	remaining: 1.16s
194:	learn: 0.1306461	total: 279ms	remaining: 1.15s
195:	learn: 0.1297944	total: 279ms	remaining: 1.15s
196:	learn: 0.1296663	total: 280ms	remaining: 1.14s
197:	learn: 0.1289368	total: 281ms	remaining: 1.14s
198:	learn: 0.1288046	total: 281ms	remaining: 1.13s
199:	learn: 0.1283525	total: 282ms	remaining: 1.13s
200:	learn: 0.1279174	total: 283ms	remaining: 1.12s
201:	learn: 0.1277216	total: 283ms	remaining: 1.12s
202:	learn: 0.1273926	total: 284ms	remaining: 1.11s
203:	learn: 0.1269093	total: 284ms	remaining: 1.11s
204:	learn: 0.1262843	total: 285ms	remaining: 1.1s
205:	learn: 0.1261823	total: 286ms	remaining: 1.1s
206:	learn: 0.1257508	total: 286ms	remaining: 1.1s
207:	learn: 0.1255844	total: 287ms	remaining: 1.09s
208:	learn: 0.1252779	total: 288ms	remaining: 1.09s
209:	learn: 0.1248470	total: 289ms	remaining: 1.08s
210:	learn: 0.1246639	total: 289ms	remaining: 1.08s
211:	learn: 0.1245668	total: 290ms	remaining: 1.08s
212:	learn: 0.1240671	total: 291ms	remaining: 1.07s
213:	learn: 0.1238521	total: 291ms	remaining: 1.07s
214:	learn: 0.1235209	total: 292ms	remaining: 1.07s
215:	learn: 0.1229562	total: 293ms	remaining: 1.06s
216:	learn: 0.1224683	total: 293ms	remaining: 1.06s
217:	learn: 0.1223108	total: 294ms	remaining: 1.05s
218:	learn: 0.1220956	total: 294ms	remaining: 1.05s
219:	learn: 0.1217158	total: 295ms	remaining: 1.04s
220:	learn: 0.1216337	total: 295ms	remaining: 1.04s
221:	learn: 0.1213119	total: 296ms	remaining: 1.04s
222:	learn: 0.1210269	total: 297ms	remaining: 1.03s
223:	learn: 0.1209038	total: 297ms	remaining: 1.03s
224:	learn: 0.1207872	total: 298ms	remaining: 1.03s
225:	learn: 0.1207114	total: 299ms	remaining: 1.02s
226:	learn: 0.1206099	total: 299ms	remaining: 1.02s
227:	learn: 0.1202360	total: 300ms	remaining: 1.01s
228:	learn: 0.1198126	total: 300ms	remaining: 1.01s
229:	learn: 0.1197142	total: 301ms	remaining: 1.01s
230:	learn: 0.1196084	total: 302ms	remaining: 1s
231:	learn: 0.1194522	total: 302ms	remaining: 1s
232:	learn: 0.1192734	total: 303ms	remaining: 998ms
233:	learn: 0.1190709	total: 304ms	remaining: 994ms
234:	learn: 0.1188613	total: 304ms	remaining: 991ms
235:	learn: 0.1187488	total: 305ms	remaining: 987ms
236:	learn: 0.1186278	total: 306ms	remaining: 984ms
237:	learn: 0.1177682	total: 306ms	remaining: 980ms
238:	learn: 0.1175476	total: 307ms	remaining: 977ms
239:	learn: 0.1169831	total: 307ms	remaining: 973ms
240:	learn: 0.1168373	total: 308ms	remaining: 970ms
241:	learn: 0.1167768	total: 309ms	remaining: 966ms
242:	learn: 0.1166481	total: 309ms	remaining: 963ms
243:	learn: 0.1165863	total: 310ms	remaining: 959ms
244:	learn: 0.1158695	total: 310ms	remaining: 956ms
245:	learn: 0.1158121	total: 311ms	remaining: 952ms
246:	learn: 0.1157538	total: 311ms	remaining: 949ms
247:	learn: 0.1155946	total: 312ms	remaining: 946ms
248:	learn: 0.1149721	total: 313ms	remaining: 943ms
249:	learn: 0.1149151	total: 313ms	remaining: 939ms
250:	learn: 0.1145696	total: 314ms	remaining: 937ms
251:	learn: 0.1143979	total: 315ms	remaining: 934ms
252:	learn: 0.1137175	total: 316ms	remaining: 933ms
253:	learn: 0.1136554	total: 317ms	remaining: 930ms
254:	learn: 0.1130851	total: 317ms	remaining: 927ms
255:	learn: 0.1129362	total: 318ms	remaining: 924ms
256:	learn: 0.1127716	total: 318ms	remaining: 921ms
257:	learn: 0.1127223	total: 319ms	remaining: 917ms
258:	learn: 0.1126616	total: 320ms	remaining: 914ms
259:	learn: 0.1120067	total: 320ms	remaining: 911ms
260:	learn: 0.1118656	total: 321ms	remaining: 908ms
261:	learn: 0.1111132	total: 321ms	remaining: 905ms
262:	learn: 0.1110703	total: 322ms	remaining: 903ms
263:	learn: 0.1103998	total: 323ms	remaining: 900ms
264:	learn: 0.1102470	total: 323ms	remaining: 897ms
265:	learn: 0.1101890	total: 324ms	remaining: 894ms
266:	learn: 0.1101357	total: 325ms	remaining: 891ms
267:	learn: 0.1097745	total: 325ms	remaining: 888ms
268:	learn: 0.1092076	total: 326ms	remaining: 885ms
269:	learn: 0.1090747	total: 326ms	remaining: 882ms
270:	learn: 0.1088644	total: 327ms	remaining: 879ms
271:	learn: 0.1082415	total: 327ms	remaining: 876ms
272:	learn: 0.1077061	total: 328ms	remaining: 874ms
273:	learn: 0.1076543	total: 329ms	remaining: 871ms
274:	learn: 0.1070127	total: 329ms	remaining: 868ms
275:	learn: 0.1064887	total: 330ms	remaining: 865ms
276:	learn: 0.1058858	total: 330ms	remaining: 862ms
277:	learn: 0.1058325	total: 332ms	remaining: 861ms
278:	learn: 0.1057160	total: 332ms	remaining: 859ms
279:	learn: 0.1055895	total: 333ms	remaining: 856ms
280:	learn: 0.1055262	total: 334ms	remaining: 854ms
281:	learn: 0.1053154	total: 334ms	remaining: 851ms
282:	learn: 0.1046801	total: 335ms	remaining: 848ms
283:	learn: 0.1046433	total: 336ms	remaining: 846ms
284:	learn: 0.1040297	total: 336ms	remaining: 843ms
285:	learn: 0.1039180	total: 337ms	remaining: 841ms
286:	learn: 0.1033120	total: 337ms	remaining: 838ms
287:	learn: 0.1032353	total: 338ms	remaining: 836ms
288:	learn: 0.1030867	total: 339ms	remaining: 833ms
289:	learn: 0.1025459	total: 339ms	remaining: 831ms
290:	learn: 0.1025007	total: 340ms	remaining: 829ms
291:	learn: 0.1024418	total: 341ms	remaining: 826ms
292:	learn: 0.1023070	total: 341ms	remaining: 824ms
293:	learn: 0.1021649	total: 342ms	remaining: 821ms
294:	learn: 0.1016434	total: 342ms	remaining: 818ms
295:	learn: 0.1015083	total: 343ms	remaining: 816ms
296:	learn: 0.1013629	total: 343ms	remaining: 813ms
297:	learn: 0.1008716	total: 344ms	remaining: 810ms
298:	learn: 0.1008144	total: 345ms	remaining: 808ms
299:	learn: 0.1007597	total: 345ms	remaining: 806ms
300:	learn: 0.1007057	total: 346ms	remaining: 804ms
301:	learn: 0.1005823	total: 347ms	remaining: 801ms
302:	learn: 0.1004792	total: 348ms	remaining: 800ms
303:	learn: 0.1003870	total: 348ms	remaining: 797ms
304:	learn: 0.1003131	total: 349ms	remaining: 794ms
305:	learn: 0.0996566	total: 349ms	remaining: 792ms
306:	learn: 0.0991613	total: 350ms	remaining: 789ms
307:	learn: 0.0990370	total: 350ms	remaining: 787ms
308:	learn: 0.0985673	total: 351ms	remaining: 784ms
309:	learn: 0.0981476	total: 351ms	remaining: 782ms
310:	learn: 0.0980247	total: 352ms	remaining: 779ms
311:	learn: 0.0978052	total: 352ms	remaining: 777ms
312:	learn: 0.0977057	total: 353ms	remaining: 774ms
313:	learn: 0.0973581	total: 353ms	remaining: 772ms
314:	learn: 0.0970550	total: 354ms	remaining: 769ms
315:	learn: 0.0968474	total: 354ms	remaining: 767ms
316:	learn: 0.0963584	total: 355ms	remaining: 764ms
317:	learn: 0.0958311	total: 355ms	remaining: 762ms
318:	learn: 0.0956614	total: 356ms	remaining: 760ms
319:	learn: 0.0953325	total: 356ms	remaining: 757ms
320:	learn: 0.0950190	total: 357ms	remaining: 755ms
321:	learn: 0.0945453	total: 357ms	remaining: 753ms
322:	learn: 0.0940853	total: 358ms	remaining: 750ms
323:	learn: 0.0938023	total: 358ms	remaining: 748ms
324:	learn: 0.0937095	total: 359ms	remaining: 746ms
325:	learn: 0.0936185	total: 360ms	remaining: 744ms
326:	learn: 0.0935437	total: 360ms	remaining: 742ms
327:	learn: 0.0934705	total: 361ms	remaining: 740ms
328:	learn: 0.0930305	total: 362ms	remaining: 738ms
329:	learn: 0.0926680	total: 362ms	remaining: 735ms
330:	learn: 0.0925350	total: 363ms	remaining: 733ms
331:	learn: 0.0923793	total: 363ms	remaining: 731ms
332:	learn: 0.0922943	total: 364ms	remaining: 729ms
333:	learn: 0.0920107	total: 365ms	remaining: 727ms
334:	learn: 0.0917872	total: 365ms	remaining: 725ms
335:	learn: 0.0916325	total: 366ms	remaining: 723ms
336:	learn: 0.0913617	total: 367ms	remaining: 722ms
337:	learn: 0.0911101	total: 368ms	remaining: 720ms
338:	learn: 0.0906460	total: 368ms	remaining: 718ms
339:	learn: 0.0906091	total: 369ms	remaining: 716ms
340:	learn: 0.0903520	total: 369ms	remaining: 714ms
341:	learn: 0.0902595	total: 370ms	remaining: 712ms
342:	learn: 0.0902116	total: 371ms	remaining: 710ms
343:	learn: 0.0899500	total: 371ms	remaining: 708ms
344:	learn: 0.0897592	total: 372ms	remaining: 706ms
345:	learn: 0.0897244	total: 372ms	remaining: 704ms
346:	learn: 0.0894939	total: 373ms	remaining: 702ms
347:	learn: 0.0893507	total: 374ms	remaining: 700ms
348:	learn: 0.0891658	total: 374ms	remaining: 698ms
349:	learn: 0.0890150	total: 375ms	remaining: 697ms
350:	learn: 0.0889233	total: 376ms	remaining: 696ms
351:	learn: 0.0886697	total: 377ms	remaining: 694ms
352:	learn: 0.0885158	total: 377ms	remaining: 692ms
353:	learn: 0.0881543	total: 378ms	remaining: 690ms
354:	learn: 0.0879230	total: 379ms	remaining: 688ms
355:	learn: 0.0878317	total: 379ms	remaining: 686ms
356:	learn: 0.0874434	total: 380ms	remaining: 684ms
357:	learn: 0.0872923	total: 381ms	remaining: 683ms
358:	learn: 0.0872108	total: 381ms	remaining: 681ms
359:	learn: 0.0870987	total: 382ms	remaining: 679ms
360:	learn: 0.0866289	total: 383ms	remaining: 677ms
361:	learn: 0.0865009	total: 383ms	remaining: 676ms
362:	learn: 0.0862363	total: 384ms	remaining: 674ms
363:	learn: 0.0859435	total: 385ms	remaining: 672ms
364:	learn: 0.0858955	total: 385ms	remaining: 670ms
365:	learn: 0.0855297	total: 386ms	remaining: 668ms
366:	learn: 0.0851849	total: 386ms	remaining: 666ms
367:	learn: 0.0846942	total: 387ms	remaining: 664ms
368:	learn: 0.0845733	total: 388ms	remaining: 663ms
369:	learn: 0.0840982	total: 388ms	remaining: 661ms
370:	learn: 0.0839926	total: 389ms	remaining: 659ms
371:	learn: 0.0839194	total: 390ms	remaining: 658ms
372:	learn: 0.0838906	total: 390ms	remaining: 656ms
373:	learn: 0.0837797	total: 391ms	remaining: 655ms
374:	learn: 0.0836620	total: 392ms	remaining: 653ms
375:	learn: 0.0835724	total: 393ms	remaining: 652ms
376:	learn: 0.0831117	total: 394ms	remaining: 651ms
377:	learn: 0.0826661	total: 394ms	remaining: 649ms
378:	learn: 0.0826344	total: 395ms	remaining: 647ms
379:	learn: 0.0821748	total: 396ms	remaining: 646ms
380:	learn: 0.0820190	total: 396ms	remaining: 644ms

In [44]:
XGB_reg_all, LGBM_reg_all, model_CB_all = train_best_reg_models(df_all, relevant_columns_all)

Error metrics for XGBoost regression model :
The median absolute error is: 0.00
The mean absolute error is: 0.14
The root mean squared error is: 0.26
Error metrics for LightGBM regression model :
The median absolute error is: 0.03
The mean absolute error is: 0.13
The root mean squared error is: 0.23
Learning rate set to 0.031087
0:	learn: 0.3003217	total: 1.02ms	remaining: 1.02s
1:	learn: 0.2973881	total: 1.8ms	remaining: 901ms
2:	learn: 0.2942856	total: 2.53ms	remaining: 841ms
3:	learn: 0.2911255	total: 3.26ms	remaining: 811ms
4:	learn: 0.2877548	total: 3.99ms	remaining: 795ms
5:	learn: 0.2850388	total: 4.68ms	remaining: 775ms
6:	learn: 0.2820048	total: 5.39ms	remaining: 764ms
7:	learn: 0.2787589	total: 6.05ms	remaining: 750ms
8:	learn: 0.2764064	total: 6.68ms	remaining: 736ms
9:	learn: 0.2738978	total: 7.36ms	remaining: 729ms
10:	learn: 0.2711580	total: 8.05ms	remaining: 724ms
11:	learn: 0.2684147	total: 8.68ms	remaining: 715ms
12:	learn: 0.2662702	total: 9.36ms	remaining: 711ms
13:	learn: 0.2640215	total: 10ms	remaining: 705ms
14:	learn: 0.2607089	total: 10.7ms	remaining: 706ms
15:	learn: 0.2583045	total: 11.6ms	remaining: 715ms
16:	learn: 0.2560694	total: 12.6ms	remaining: 728ms
17:	learn: 0.2540452	total: 13.6ms	remaining: 742ms
18:	learn: 0.2519371	total: 14.4ms	remaining: 746ms
19:	learn: 0.2497220	total: 15.2ms	remaining: 747ms
20:	learn: 0.2469085	total: 16ms	remaining: 744ms
21:	learn: 0.2450665	total: 16.7ms	remaining: 740ms
22:	learn: 0.2432085	total: 17.4ms	remaining: 739ms
23:	learn: 0.2413995	total: 18.1ms	remaining: 736ms
24:	learn: 0.2395091	total: 18.7ms	remaining: 731ms
25:	learn: 0.2377139	total: 19.4ms	remaining: 726ms
26:	learn: 0.2354517	total: 20.3ms	remaining: 730ms
27:	learn: 0.2330743	total: 20.9ms	remaining: 727ms
28:	learn: 0.2315159	total: 21.6ms	remaining: 723ms
29:	learn: 0.2295555	total: 22.3ms	remaining: 721ms
30:	learn: 0.2274768	total: 23ms	remaining: 719ms
31:	learn: 0.2258550	total: 23.7ms	remaining: 718ms
32:	learn: 0.2238080	total: 24.5ms	remaining: 717ms
33:	learn: 0.2224259	total: 25.1ms	remaining: 714ms
34:	learn: 0.2210981	total: 25.8ms	remaining: 711ms
35:	learn: 0.2194063	total: 26.9ms	remaining: 720ms
36:	learn: 0.2178732	total: 27.7ms	remaining: 720ms
37:	learn: 0.2162154	total: 28.7ms	remaining: 727ms
38:	learn: 0.2145968	total: 29.8ms	remaining: 733ms
39:	learn: 0.2130295	total: 30.6ms	remaining: 734ms
40:	learn: 0.2111516	total: 31.5ms	remaining: 736ms
41:	learn: 0.2098716	total: 32.2ms	remaining: 734ms
42:	learn: 0.2087179	total: 33ms	remaining: 733ms
43:	learn: 0.2072298	total: 33.7ms	remaining: 733ms
44:	learn: 0.2049579	total: 34.5ms	remaining: 732ms
45:	learn: 0.2031370	total: 35.3ms	remaining: 733ms
46:	learn: 0.2018372	total: 36.2ms	remaining: 734ms
47:	learn: 0.2003227	total: 37ms	remaining: 734ms
48:	learn: 0.1993141	total: 38.9ms	remaining: 755ms
49:	learn: 0.1979332	total: 39.7ms	remaining: 754ms
50:	learn: 0.1967485	total: 40.8ms	remaining: 759ms
51:	learn: 0.1947712	total: 41.6ms	remaining: 758ms
52:	learn: 0.1939148	total: 42.6ms	remaining: 761ms
53:	learn: 0.1925407	total: 43.4ms	remaining: 760ms
54:	learn: 0.1909904	total: 44.2ms	remaining: 759ms
55:	learn: 0.1899218	total: 44.9ms	remaining: 757ms
56:	learn: 0.1885103	total: 45.8ms	remaining: 758ms
57:	learn: 0.1875484	total: 46.6ms	remaining: 757ms
58:	learn: 0.1868862	total: 47.3ms	remaining: 754ms
59:	learn: 0.1862005	total: 48.3ms	remaining: 756ms
60:	learn: 0.1853858	total: 49.7ms	remaining: 765ms
61:	learn: 0.1847768	total: 50.1ms	remaining: 758ms
62:	learn: 0.1837469	total: 50.7ms	remaining: 754ms
63:	learn: 0.1828894	total: 51.4ms	remaining: 751ms
64:	learn: 0.1818008	total: 52.1ms	remaining: 749ms
65:	learn: 0.1803493	total: 52.8ms	remaining: 747ms
66:	learn: 0.1793266	total: 53.5ms	remaining: 745ms
67:	learn: 0.1785539	total: 54.2ms	remaining: 742ms
68:	learn: 0.1775938	total: 54.8ms	remaining: 740ms
69:	learn: 0.1759935	total: 55.4ms	remaining: 736ms
70:	learn: 0.1747915	total: 56.2ms	remaining: 735ms
71:	learn: 0.1737717	total: 56.9ms	remaining: 733ms
72:	learn: 0.1728707	total: 57.7ms	remaining: 733ms
73:	learn: 0.1713711	total: 58.6ms	remaining: 733ms
74:	learn: 0.1705452	total: 59.4ms	remaining: 733ms
75:	learn: 0.1696789	total: 60.1ms	remaining: 731ms
76:	learn: 0.1687175	total: 60.9ms	remaining: 730ms
77:	learn: 0.1674754	total: 61.6ms	remaining: 728ms
78:	learn: 0.1665535	total: 62.3ms	remaining: 726ms
79:	learn: 0.1655258	total: 63.1ms	remaining: 725ms
80:	learn: 0.1646123	total: 63.8ms	remaining: 724ms
81:	learn: 0.1635933	total: 64.6ms	remaining: 723ms
82:	learn: 0.1626866	total: 65.3ms	remaining: 722ms
83:	learn: 0.1617201	total: 66ms	remaining: 720ms
84:	learn: 0.1609630	total: 66.8ms	remaining: 719ms
85:	learn: 0.1594568	total: 67.5ms	remaining: 718ms
86:	learn: 0.1581562	total: 68.3ms	remaining: 717ms
87:	learn: 0.1571973	total: 69.6ms	remaining: 721ms
88:	learn: 0.1560834	total: 70.4ms	remaining: 720ms
89:	learn: 0.1550712	total: 71.2ms	remaining: 720ms
90:	learn: 0.1545047	total: 71.9ms	remaining: 718ms
91:	learn: 0.1535783	total: 72.9ms	remaining: 719ms
92:	learn: 0.1527797	total: 74ms	remaining: 721ms
93:	learn: 0.1515641	total: 75ms	remaining: 723ms
94:	learn: 0.1507740	total: 75.8ms	remaining: 722ms
95:	learn: 0.1494626	total: 76.6ms	remaining: 721ms
96:	learn: 0.1489534	total: 77.5ms	remaining: 721ms
97:	learn: 0.1481902	total: 78.3ms	remaining: 721ms
98:	learn: 0.1473696	total: 79.2ms	remaining: 721ms
99:	learn: 0.1465172	total: 80ms	remaining: 720ms
100:	learn: 0.1450778	total: 80.7ms	remaining: 718ms
101:	learn: 0.1442154	total: 81.4ms	remaining: 716ms
102:	learn: 0.1437389	total: 82ms	remaining: 714ms
103:	learn: 0.1430473	total: 82.8ms	remaining: 713ms
104:	learn: 0.1426305	total: 83.5ms	remaining: 712ms
105:	learn: 0.1420060	total: 84.1ms	remaining: 710ms
106:	learn: 0.1412096	total: 84.8ms	remaining: 707ms
107:	learn: 0.1407368	total: 85.5ms	remaining: 706ms
108:	learn: 0.1399488	total: 86.1ms	remaining: 704ms
109:	learn: 0.1391933	total: 87.3ms	remaining: 707ms
110:	learn: 0.1383389	total: 88.3ms	remaining: 708ms
111:	learn: 0.1375096	total: 89.2ms	remaining: 707ms
112:	learn: 0.1367502	total: 89.9ms	remaining: 706ms
113:	learn: 0.1359924	total: 90.5ms	remaining: 704ms
114:	learn: 0.1353626	total: 91.2ms	remaining: 702ms
115:	learn: 0.1344161	total: 92.1ms	remaining: 702ms
116:	learn: 0.1336171	total: 92.8ms	remaining: 700ms
117:	learn: 0.1326227	total: 93.4ms	remaining: 698ms
118:	learn: 0.1319520	total: 94.1ms	remaining: 697ms
119:	learn: 0.1311396	total: 94.9ms	remaining: 696ms
120:	learn: 0.1304191	total: 95.6ms	remaining: 695ms
121:	learn: 0.1299396	total: 96.3ms	remaining: 693ms
122:	learn: 0.1295199	total: 96.9ms	remaining: 691ms
123:	learn: 0.1286504	total: 97.6ms	remaining: 689ms
124:	learn: 0.1280626	total: 98.2ms	remaining: 687ms
125:	learn: 0.1274480	total: 98.8ms	remaining: 685ms
126:	learn: 0.1265140	total: 99.5ms	remaining: 684ms
127:	learn: 0.1259868	total: 100ms	remaining: 683ms
128:	learn: 0.1253399	total: 101ms	remaining: 682ms
129:	learn: 0.1247397	total: 102ms	remaining: 683ms
130:	learn: 0.1240081	total: 103ms	remaining: 682ms
131:	learn: 0.1232706	total: 104ms	remaining: 682ms
132:	learn: 0.1226960	total: 105ms	remaining: 682ms
133:	learn: 0.1222544	total: 105ms	remaining: 680ms
134:	learn: 0.1216062	total: 106ms	remaining: 679ms
135:	learn: 0.1210481	total: 107ms	remaining: 678ms
136:	learn: 0.1202979	total: 107ms	remaining: 676ms
137:	learn: 0.1198263	total: 108ms	remaining: 674ms
138:	learn: 0.1193629	total: 109ms	remaining: 672ms
139:	learn: 0.1191107	total: 109ms	remaining: 671ms
140:	learn: 0.1184346	total: 110ms	remaining: 669ms
141:	learn: 0.1181132	total: 111ms	remaining: 668ms
142:	learn: 0.1173901	total: 111ms	remaining: 666ms
143:	learn: 0.1167605	total: 112ms	remaining: 665ms
144:	learn: 0.1161558	total: 112ms	remaining: 663ms
145:	learn: 0.1157382	total: 113ms	remaining: 661ms
146:	learn: 0.1155062	total: 114ms	remaining: 659ms
147:	learn: 0.1148974	total: 114ms	remaining: 658ms
148:	learn: 0.1147374	total: 115ms	remaining: 656ms
149:	learn: 0.1143011	total: 115ms	remaining: 654ms
150:	learn: 0.1137883	total: 116ms	remaining: 653ms
151:	learn: 0.1131912	total: 117ms	remaining: 653ms
152:	learn: 0.1128518	total: 118ms	remaining: 654ms
153:	learn: 0.1125088	total: 119ms	remaining: 653ms
154:	learn: 0.1117685	total: 120ms	remaining: 653ms
155:	learn: 0.1112234	total: 120ms	remaining: 652ms
156:	learn: 0.1105542	total: 121ms	remaining: 650ms
157:	learn: 0.1098340	total: 122ms	remaining: 648ms
158:	learn: 0.1095898	total: 122ms	remaining: 647ms
159:	learn: 0.1086750	total: 123ms	remaining: 646ms
160:	learn: 0.1078769	total: 124ms	remaining: 645ms
161:	learn: 0.1074684	total: 124ms	remaining: 643ms
162:	learn: 0.1069946	total: 125ms	remaining: 642ms
163:	learn: 0.1064880	total: 126ms	remaining: 640ms
164:	learn: 0.1059814	total: 126ms	remaining: 638ms
165:	learn: 0.1054039	total: 127ms	remaining: 638ms
166:	learn: 0.1049904	total: 128ms	remaining: 636ms
167:	learn: 0.1043280	total: 128ms	remaining: 635ms
168:	learn: 0.1038376	total: 129ms	remaining: 633ms
169:	learn: 0.1033745	total: 130ms	remaining: 632ms
170:	learn: 0.1029356	total: 130ms	remaining: 631ms
171:	learn: 0.1024031	total: 131ms	remaining: 630ms
172:	learn: 0.1018133	total: 132ms	remaining: 630ms
173:	learn: 0.1009745	total: 133ms	remaining: 629ms
174:	learn: 0.1005012	total: 133ms	remaining: 629ms
175:	learn: 0.1000041	total: 134ms	remaining: 629ms
176:	learn: 0.0995471	total: 135ms	remaining: 627ms
177:	learn: 0.0990337	total: 136ms	remaining: 627ms
178:	learn: 0.0986702	total: 136ms	remaining: 625ms
179:	learn: 0.0982991	total: 137ms	remaining: 624ms
180:	learn: 0.0979815	total: 138ms	remaining: 622ms
181:	learn: 0.0976236	total: 138ms	remaining: 621ms
182:	learn: 0.0972063	total: 139ms	remaining: 620ms
183:	learn: 0.0964852	total: 139ms	remaining: 618ms
184:	learn: 0.0958828	total: 140ms	remaining: 617ms
185:	learn: 0.0952333	total: 141ms	remaining: 615ms
186:	learn: 0.0946215	total: 141ms	remaining: 614ms
187:	learn: 0.0944299	total: 142ms	remaining: 613ms
188:	learn: 0.0939935	total: 143ms	remaining: 612ms
189:	learn: 0.0934291	total: 143ms	remaining: 610ms
190:	learn: 0.0931802	total: 144ms	remaining: 609ms
191:	learn: 0.0926367	total: 144ms	remaining: 607ms
192:	learn: 0.0921234	total: 145ms	remaining: 606ms
193:	learn: 0.0916840	total: 146ms	remaining: 605ms
194:	learn: 0.0914036	total: 147ms	remaining: 607ms
195:	learn: 0.0908676	total: 148ms	remaining: 606ms
196:	learn: 0.0902784	total: 148ms	remaining: 605ms
197:	learn: 0.0898908	total: 149ms	remaining: 604ms
198:	learn: 0.0894087	total: 150ms	remaining: 602ms
199:	learn: 0.0891527	total: 150ms	remaining: 601ms
200:	learn: 0.0887406	total: 151ms	remaining: 600ms
201:	learn: 0.0883207	total: 151ms	remaining: 598ms
202:	learn: 0.0877784	total: 152ms	remaining: 597ms
203:	learn: 0.0876554	total: 153ms	remaining: 596ms
204:	learn: 0.0872958	total: 153ms	remaining: 595ms
205:	learn: 0.0867500	total: 154ms	remaining: 594ms
206:	learn: 0.0863500	total: 155ms	remaining: 593ms
207:	learn: 0.0860044	total: 155ms	remaining: 592ms
208:	learn: 0.0857732	total: 156ms	remaining: 591ms
209:	learn: 0.0856709	total: 157ms	remaining: 589ms
210:	learn: 0.0851303	total: 157ms	remaining: 588ms
211:	learn: 0.0849844	total: 158ms	remaining: 587ms
212:	learn: 0.0846498	total: 158ms	remaining: 585ms
213:	learn: 0.0842719	total: 159ms	remaining: 584ms
214:	learn: 0.0838313	total: 160ms	remaining: 583ms
215:	learn: 0.0832877	total: 160ms	remaining: 582ms
216:	learn: 0.0828311	total: 161ms	remaining: 581ms
217:	learn: 0.0823934	total: 162ms	remaining: 581ms
218:	learn: 0.0818252	total: 163ms	remaining: 581ms
219:	learn: 0.0815795	total: 164ms	remaining: 580ms
220:	learn: 0.0811226	total: 164ms	remaining: 579ms
221:	learn: 0.0806938	total: 165ms	remaining: 578ms
222:	learn: 0.0803408	total: 166ms	remaining: 577ms
223:	learn: 0.0798379	total: 166ms	remaining: 576ms
224:	learn: 0.0795464	total: 167ms	remaining: 574ms
225:	learn: 0.0793610	total: 167ms	remaining: 573ms
226:	learn: 0.0788364	total: 168ms	remaining: 572ms
227:	learn: 0.0783192	total: 168ms	remaining: 570ms
228:	learn: 0.0777836	total: 169ms	remaining: 569ms
229:	learn: 0.0775147	total: 170ms	remaining: 567ms
230:	learn: 0.0773901	total: 170ms	remaining: 566ms
231:	learn: 0.0771027	total: 171ms	remaining: 565ms
232:	learn: 0.0764903	total: 171ms	remaining: 564ms
233:	learn: 0.0760470	total: 172ms	remaining: 564ms
234:	learn: 0.0756446	total: 173ms	remaining: 562ms
235:	learn: 0.0753619	total: 173ms	remaining: 561ms
236:	learn: 0.0749637	total: 174ms	remaining: 560ms
237:	learn: 0.0748727	total: 175ms	remaining: 559ms
238:	learn: 0.0744255	total: 175ms	remaining: 558ms
239:	learn: 0.0739536	total: 176ms	remaining: 558ms
240:	learn: 0.0734926	total: 177ms	remaining: 558ms
241:	learn: 0.0732143	total: 178ms	remaining: 557ms
242:	learn: 0.0728922	total: 178ms	remaining: 555ms
243:	learn: 0.0726106	total: 179ms	remaining: 554ms
244:	learn: 0.0722668	total: 179ms	remaining: 553ms
245:	learn: 0.0719338	total: 180ms	remaining: 552ms
246:	learn: 0.0716948	total: 181ms	remaining: 551ms
247:	learn: 0.0716062	total: 181ms	remaining: 550ms
248:	learn: 0.0711614	total: 182ms	remaining: 549ms
249:	learn: 0.0708036	total: 183ms	remaining: 548ms
250:	learn: 0.0707245	total: 183ms	remaining: 547ms
251:	learn: 0.0704143	total: 184ms	remaining: 546ms
252:	learn: 0.0701909	total: 184ms	remaining: 545ms
253:	learn: 0.0698558	total: 185ms	remaining: 543ms
254:	learn: 0.0695479	total: 186ms	remaining: 542ms
255:	learn: 0.0691012	total: 186ms	remaining: 541ms
256:	learn: 0.0687081	total: 187ms	remaining: 540ms
257:	learn: 0.0684335	total: 187ms	remaining: 539ms
258:	learn: 0.0681390	total: 188ms	remaining: 538ms
259:	learn: 0.0680321	total: 189ms	remaining: 537ms
260:	learn: 0.0679095	total: 189ms	remaining: 536ms
261:	learn: 0.0675083	total: 190ms	remaining: 535ms
262:	learn: 0.0672289	total: 191ms	remaining: 535ms
263:	learn: 0.0671404	total: 192ms	remaining: 534ms
264:	learn: 0.0667488	total: 192ms	remaining: 534ms
265:	learn: 0.0663656	total: 193ms	remaining: 533ms
266:	learn: 0.0661137	total: 194ms	remaining: 532ms
267:	learn: 0.0658441	total: 195ms	remaining: 532ms
268:	learn: 0.0655728	total: 195ms	remaining: 531ms
269:	learn: 0.0652600	total: 196ms	remaining: 530ms
270:	learn: 0.0650200	total: 197ms	remaining: 529ms
271:	learn: 0.0646547	total: 197ms	remaining: 528ms
272:	learn: 0.0645306	total: 198ms	remaining: 527ms
273:	learn: 0.0643000	total: 199ms	remaining: 526ms
274:	learn: 0.0638707	total: 199ms	remaining: 526ms
275:	learn: 0.0636223	total: 200ms	remaining: 525ms
276:	learn: 0.0635061	total: 201ms	remaining: 524ms
277:	learn: 0.0632637	total: 201ms	remaining: 523ms
278:	learn: 0.0630292	total: 202ms	remaining: 521ms
279:	learn: 0.0627769	total: 202ms	remaining: 520ms
280:	learn: 0.0626306	total: 203ms	remaining: 519ms
281:	learn: 0.0625167	total: 204ms	remaining: 518ms
282:	learn: 0.0622647	total: 204ms	remaining: 517ms
283:	learn: 0.0620316	total: 205ms	remaining: 516ms
284:	learn: 0.0619193	total: 205ms	remaining: 515ms
285:	learn: 0.0618090	total: 206ms	remaining: 515ms
286:	learn: 0.0617543	total: 207ms	remaining: 514ms
287:	learn: 0.0615344	total: 208ms	remaining: 513ms
288:	learn: 0.0613950	total: 208ms	remaining: 512ms
289:	learn: 0.0612735	total: 209ms	remaining: 511ms
290:	learn: 0.0609391	total: 209ms	remaining: 510ms
291:	learn: 0.0605813	total: 210ms	remaining: 509ms
292:	learn: 0.0602647	total: 211ms	remaining: 508ms
293:	learn: 0.0600211	total: 211ms	remaining: 507ms
294:	learn: 0.0597920	total: 212ms	remaining: 506ms
295:	learn: 0.0597418	total: 213ms	remaining: 506ms
296:	learn: 0.0593995	total: 213ms	remaining: 505ms
297:	learn: 0.0592262	total: 214ms	remaining: 504ms
298:	learn: 0.0589161	total: 215ms	remaining: 504ms
299:	learn: 0.0587351	total: 216ms	remaining: 503ms
300:	learn: 0.0583926	total: 216ms	remaining: 502ms
301:	learn: 0.0581220	total: 217ms	remaining: 501ms
302:	learn: 0.0578578	total: 218ms	remaining: 501ms
303:	learn: 0.0577252	total: 219ms	remaining: 500ms
304:	learn: 0.0574331	total: 219ms	remaining: 500ms
305:	learn: 0.0571504	total: 221ms	remaining: 501ms
306:	learn: 0.0569379	total: 221ms	remaining: 500ms
307:	learn: 0.0567839	total: 222ms	remaining: 499ms
308:	learn: 0.0565557	total: 223ms	remaining: 499ms
309:	learn: 0.0563194	total: 224ms	remaining: 498ms
310:	learn: 0.0561908	total: 225ms	remaining: 498ms
311:	learn: 0.0560631	total: 225ms	remaining: 497ms
312:	learn: 0.0559378	total: 226ms	remaining: 496ms
313:	learn: 0.0557295	total: 227ms	remaining: 496ms
314:	learn: 0.0555277	total: 228ms	remaining: 495ms
315:	learn: 0.0553014	total: 228ms	remaining: 494ms
316:	learn: 0.0551233	total: 229ms	remaining: 494ms
317:	learn: 0.0549773	total: 230ms	remaining: 493ms
318:	learn: 0.0547104	total: 231ms	remaining: 492ms
319:	learn: 0.0545687	total: 231ms	remaining: 492ms
320:	learn: 0.0543238	total: 232ms	remaining: 491ms
321:	learn: 0.0542029	total: 233ms	remaining: 490ms
322:	learn: 0.0541018	total: 233ms	remaining: 489ms
323:	learn: 0.0539080	total: 234ms	remaining: 488ms
324:	learn: 0.0538486	total: 235ms	remaining: 488ms
325:	learn: 0.0537828	total: 236ms	remaining: 488ms
326:	learn: 0.0536650	total: 237ms	remaining: 487ms
327:	learn: 0.0535030	total: 238ms	remaining: 487ms
328:	learn: 0.0533064	total: 239ms	remaining: 487ms
329:	learn: 0.0531765	total: 239ms	remaining: 486ms
330:	learn: 0.0529761	total: 240ms	remaining: 486ms
331:	learn: 0.0526883	total: 241ms	remaining: 486ms
332:	learn: 0.0525759	total: 242ms	remaining: 485ms
333:	learn: 0.0522925	total: 243ms	remaining: 485ms
334:	learn: 0.0522296	total: 244ms	remaining: 484ms
335:	learn: 0.0521681	total: 244ms	remaining: 483ms
336:	learn: 0.0519647	total: 245ms	remaining: 482ms
337:	learn: 0.0518668	total: 246ms	remaining: 481ms
338:	learn: 0.0517755	total: 246ms	remaining: 480ms
339:	learn: 0.0514404	total: 247ms	remaining: 479ms
340:	learn: 0.0512676	total: 247ms	remaining: 478ms
341:	learn: 0.0510984	total: 248ms	remaining: 477ms
342:	learn: 0.0509828	total: 248ms	remaining: 476ms
343:	learn: 0.0509246	total: 249ms	remaining: 475ms
344:	learn: 0.0507622	total: 250ms	remaining: 475ms
345:	learn: 0.0506578	total: 251ms	remaining: 474ms
346:	learn: 0.0504476	total: 252ms	remaining: 474ms
347:	learn: 0.0503355	total: 253ms	remaining: 473ms
348:	learn: 0.0501761	total: 253ms	remaining: 472ms
349:	learn: 0.0500242	total: 254ms	remaining: 472ms
350:	learn: 0.0497041	total: 255ms	remaining: 471ms
351:	learn: 0.0494936	total: 255ms	remaining: 470ms
352:	learn: 0.0493359	total: 256ms	remaining: 469ms
353:	learn: 0.0491962	total: 257ms	remaining: 468ms
354:	learn: 0.0490800	total: 257ms	remaining: 467ms
355:	learn: 0.0489723	total: 258ms	remaining: 467ms
356:	learn: 0.0486852	total: 259ms	remaining: 466ms
357:	learn: 0.0484377	total: 259ms	remaining: 465ms
358:	learn: 0.0481948	total: 260ms	remaining: 464ms
359:	learn: 0.0480900	total: 260ms	remaining: 463ms
360:	learn: 0.0478960	total: 261ms	remaining: 462ms
361:	learn: 0.0476882	total: 262ms	remaining: 461ms
362:	learn: 0.0475857	total: 262ms	remaining: 460ms
363:	learn: 0.0473906	total: 263ms	remaining: 459ms
364:	learn: 0.0472735	total: 264ms	remaining: 459ms
365:	learn: 0.0471790	total: 265ms	remaining: 458ms
366:	learn: 0.0470791	total: 266ms	remaining: 458ms
367:	learn: 0.0467906	total: 267ms	remaining: 458ms
368:	learn: 0.0466204	total: 267ms	remaining: 457ms
369:	learn: 0.0464341	total: 268ms	remaining: 456ms
370:	learn: 0.0462720	total: 269ms	remaining: 456ms
371:	learn: 0.0460151	total: 270ms	remaining: 455ms
372:	learn: 0.0458839	total: 270ms	remaining: 454ms
373:	learn: 0.0457540	total: 271ms	remaining: 453ms
374:	learn: 0.0456640	total: 271ms	remaining: 452ms
375:	learn: 0.0454702	total: 272ms	remaining: 452ms
376:	learn: 0.0452957	total: 273ms	remaining: 451ms
377:	learn: 0.0451921	total: 273ms	remaining: 450ms

In [45]:
XGB_reg_all_plus_plus, LGBM_reg_all_plus_plus, model_CB_all_plus_plus = train_best_reg_models(df_all_plus_plus, relevant_columns_all_plus_plus)

Error metrics for XGBoost regression model :
The median absolute error is: 0.02
The mean absolute error is: 0.15
The root mean squared error is: 0.27
Error metrics for LightGBM regression model :
The median absolute error is: 0.05
The mean absolute error is: 0.15
The root mean squared error is: 0.26
Learning rate set to 0.029768
0:	learn: 0.3339038	total: 1.26ms	remaining: 1.26s
1:	learn: 0.3296660	total: 2.91ms	remaining: 1.45s
2:	learn: 0.3259666	total: 4.21ms	remaining: 1.4s
3:	learn: 0.3220462	total: 5.36ms	remaining: 1.33s
4:	learn: 0.3182144	total: 6.65ms	remaining: 1.32s
5:	learn: 0.3145398	total: 7.89ms	remaining: 1.31s
6:	learn: 0.3106101	total: 9.01ms	remaining: 1.28s
7:	learn: 0.3070298	total: 10.2ms	remaining: 1.26s
8:	learn: 0.3036900	total: 11.3ms	remaining: 1.24s
9:	learn: 0.2999627	total: 12.4ms	remaining: 1.23s
10:	learn: 0.2964252	total: 13.5ms	remaining: 1.22s
11:	learn: 0.2922302	total: 14.7ms	remaining: 1.21s
12:	learn: 0.2887082	total: 16.1ms	remaining: 1.22s
13:	learn: 0.2857541	total: 17.5ms	remaining: 1.23s
14:	learn: 0.2828172	total: 18.8ms	remaining: 1.23s
15:	learn: 0.2798555	total: 20ms	remaining: 1.23s
16:	learn: 0.2772897	total: 21.4ms	remaining: 1.24s
17:	learn: 0.2745138	total: 22.5ms	remaining: 1.23s
18:	learn: 0.2716565	total: 23.7ms	remaining: 1.22s
19:	learn: 0.2688600	total: 24.8ms	remaining: 1.22s
20:	learn: 0.2658785	total: 26ms	remaining: 1.21s
21:	learn: 0.2629920	total: 27.2ms	remaining: 1.21s
22:	learn: 0.2606300	total: 28.4ms	remaining: 1.21s
23:	learn: 0.2576741	total: 29.5ms	remaining: 1.2s
24:	learn: 0.2551879	total: 30.7ms	remaining: 1.2s
25:	learn: 0.2523924	total: 32.8ms	remaining: 1.23s
26:	learn: 0.2502892	total: 34.1ms	remaining: 1.23s
27:	learn: 0.2476871	total: 35.3ms	remaining: 1.23s
28:	learn: 0.2455063	total: 36.6ms	remaining: 1.22s
29:	learn: 0.2426122	total: 37.7ms	remaining: 1.22s
30:	learn: 0.2398079	total: 38.8ms	remaining: 1.21s
31:	learn: 0.2374074	total: 40ms	remaining: 1.21s
32:	learn: 0.2354601	total: 41.2ms	remaining: 1.21s
33:	learn: 0.2332282	total: 42.4ms	remaining: 1.2s
34:	learn: 0.2305012	total: 43.5ms	remaining: 1.2s
35:	learn: 0.2286984	total: 44.6ms	remaining: 1.2s
36:	learn: 0.2273928	total: 45.9ms	remaining: 1.19s
37:	learn: 0.2251681	total: 47.1ms	remaining: 1.19s
38:	learn: 0.2228676	total: 48.6ms	remaining: 1.2s
39:	learn: 0.2212222	total: 49.8ms	remaining: 1.2s
40:	learn: 0.2191686	total: 51ms	remaining: 1.19s
41:	learn: 0.2174863	total: 51.7ms	remaining: 1.18s
42:	learn: 0.2154520	total: 53ms	remaining: 1.18s
43:	learn: 0.2133418	total: 54.3ms	remaining: 1.18s
44:	learn: 0.2109602	total: 55.4ms	remaining: 1.18s
45:	learn: 0.2094867	total: 56.6ms	remaining: 1.17s
46:	learn: 0.2079190	total: 57.6ms	remaining: 1.17s
47:	learn: 0.2061434	total: 58.7ms	remaining: 1.16s
48:	learn: 0.2046050	total: 59.9ms	remaining: 1.16s
49:	learn: 0.2030317	total: 61ms	remaining: 1.16s
50:	learn: 0.2011925	total: 62.2ms	remaining: 1.16s
51:	learn: 0.1999186	total: 64ms	remaining: 1.17s
52:	learn: 0.1983478	total: 65.5ms	remaining: 1.17s
53:	learn: 0.1968290	total: 66.6ms	remaining: 1.17s
54:	learn: 0.1953026	total: 67.7ms	remaining: 1.16s
55:	learn: 0.1941222	total: 68.9ms	remaining: 1.16s
56:	learn: 0.1928388	total: 70ms	remaining: 1.16s
57:	learn: 0.1912624	total: 71.2ms	remaining: 1.16s
58:	learn: 0.1895508	total: 72.5ms	remaining: 1.16s
59:	learn: 0.1877815	total: 73.6ms	remaining: 1.15s
60:	learn: 0.1863507	total: 74.8ms	remaining: 1.15s
61:	learn: 0.1856568	total: 76ms	remaining: 1.15s
62:	learn: 0.1843713	total: 77.1ms	remaining: 1.15s
63:	learn: 0.1827739	total: 78.2ms	remaining: 1.14s
64:	learn: 0.1810645	total: 79.4ms	remaining: 1.14s
65:	learn: 0.1800815	total: 80.6ms	remaining: 1.14s
66:	learn: 0.1790751	total: 81.8ms	remaining: 1.14s
67:	learn: 0.1780648	total: 83ms	remaining: 1.14s
68:	learn: 0.1771232	total: 84.2ms	remaining: 1.14s
69:	learn: 0.1757555	total: 85.3ms	remaining: 1.13s
70:	learn: 0.1745721	total: 86.4ms	remaining: 1.13s
71:	learn: 0.1735374	total: 87.5ms	remaining: 1.13s
72:	learn: 0.1726572	total: 88.6ms	remaining: 1.13s
73:	learn: 0.1714334	total: 89.7ms	remaining: 1.12s
74:	learn: 0.1703077	total: 90.8ms	remaining: 1.12s
75:	learn: 0.1691195	total: 91.8ms	remaining: 1.11s
76:	learn: 0.1677811	total: 93ms	remaining: 1.11s
77:	learn: 0.1670322	total: 94.3ms	remaining: 1.11s
78:	learn: 0.1659562	total: 95.5ms	remaining: 1.11s
79:	learn: 0.1644677	total: 96.6ms	remaining: 1.11s
80:	learn: 0.1633020	total: 97.7ms	remaining: 1.11s
81:	learn: 0.1623181	total: 98.7ms	remaining: 1.1s
82:	learn: 0.1613566	total: 99.9ms	remaining: 1.1s
83:	learn: 0.1600861	total: 101ms	remaining: 1.1s
84:	learn: 0.1595597	total: 102ms	remaining: 1.1s
85:	learn: 0.1585080	total: 103ms	remaining: 1.09s
86:	learn: 0.1576142	total: 104ms	remaining: 1.09s
87:	learn: 0.1566214	total: 105ms	remaining: 1.09s
88:	learn: 0.1555268	total: 106ms	remaining: 1.08s
89:	learn: 0.1545313	total: 107ms	remaining: 1.08s
90:	learn: 0.1533636	total: 108ms	remaining: 1.08s
91:	learn: 0.1522045	total: 109ms	remaining: 1.07s
92:	learn: 0.1511122	total: 110ms	remaining: 1.07s
93:	learn: 0.1504374	total: 111ms	remaining: 1.07s
94:	learn: 0.1494355	total: 112ms	remaining: 1.07s
95:	learn: 0.1488958	total: 113ms	remaining: 1.07s
96:	learn: 0.1479796	total: 115ms	remaining: 1.07s
97:	learn: 0.1472427	total: 116ms	remaining: 1.06s
98:	learn: 0.1464240	total: 117ms	remaining: 1.06s
99:	learn: 0.1454446	total: 118ms	remaining: 1.06s
100:	learn: 0.1447631	total: 119ms	remaining: 1.06s
101:	learn: 0.1439316	total: 120ms	remaining: 1.06s
102:	learn: 0.1428717	total: 121ms	remaining: 1.05s
103:	learn: 0.1423812	total: 122ms	remaining: 1.05s
104:	learn: 0.1412878	total: 123ms	remaining: 1.05s
105:	learn: 0.1402138	total: 124ms	remaining: 1.05s
106:	learn: 0.1395216	total: 125ms	remaining: 1.05s
107:	learn: 0.1388545	total: 126ms	remaining: 1.04s
108:	learn: 0.1378336	total: 128ms	remaining: 1.04s
109:	learn: 0.1371784	total: 129ms	remaining: 1.04s
110:	learn: 0.1365898	total: 130ms	remaining: 1.04s
111:	learn: 0.1362583	total: 131ms	remaining: 1.04s
112:	learn: 0.1351762	total: 132ms	remaining: 1.03s
113:	learn: 0.1343070	total: 133ms	remaining: 1.03s
114:	learn: 0.1337411	total: 134ms	remaining: 1.03s
115:	learn: 0.1332050	total: 135ms	remaining: 1.03s
116:	learn: 0.1327590	total: 136ms	remaining: 1.02s
117:	learn: 0.1321385	total: 137ms	remaining: 1.02s
118:	learn: 0.1312065	total: 138ms	remaining: 1.02s
119:	learn: 0.1301395	total: 139ms	remaining: 1.02s
120:	learn: 0.1294247	total: 140ms	remaining: 1.01s
121:	learn: 0.1288383	total: 141ms	remaining: 1.01s
122:	learn: 0.1279516	total: 142ms	remaining: 1.01s
123:	learn: 0.1271545	total: 143ms	remaining: 1.01s
124:	learn: 0.1260327	total: 144ms	remaining: 1.01s
125:	learn: 0.1253531	total: 145ms	remaining: 1.01s
126:	learn: 0.1247104	total: 146ms	remaining: 1.01s
127:	learn: 0.1239179	total: 147ms	remaining: 1s
128:	learn: 0.1231101	total: 148ms	remaining: 1s
129:	learn: 0.1223296	total: 149ms	remaining: 1000ms
130:	learn: 0.1217325	total: 150ms	remaining: 998ms
131:	learn: 0.1210894	total: 151ms	remaining: 996ms
132:	learn: 0.1202886	total: 153ms	remaining: 994ms
133:	learn: 0.1196678	total: 154ms	remaining: 992ms
134:	learn: 0.1189714	total: 155ms	remaining: 993ms
135:	learn: 0.1184305	total: 157ms	remaining: 996ms
136:	learn: 0.1180439	total: 158ms	remaining: 995ms
137:	learn: 0.1173884	total: 159ms	remaining: 993ms
138:	learn: 0.1166575	total: 160ms	remaining: 991ms
139:	learn: 0.1161462	total: 161ms	remaining: 989ms
140:	learn: 0.1153042	total: 162ms	remaining: 986ms
141:	learn: 0.1145606	total: 163ms	remaining: 984ms
142:	learn: 0.1141614	total: 164ms	remaining: 983ms
143:	learn: 0.1135860	total: 165ms	remaining: 981ms
144:	learn: 0.1129620	total: 166ms	remaining: 979ms
145:	learn: 0.1124096	total: 167ms	remaining: 977ms
146:	learn: 0.1116630	total: 168ms	remaining: 975ms
147:	learn: 0.1109346	total: 169ms	remaining: 973ms
148:	learn: 0.1106989	total: 170ms	remaining: 972ms
149:	learn: 0.1100873	total: 172ms	remaining: 973ms
150:	learn: 0.1096179	total: 173ms	remaining: 973ms
151:	learn: 0.1091255	total: 174ms	remaining: 973ms
152:	learn: 0.1084869	total: 175ms	remaining: 972ms
153:	learn: 0.1080188	total: 177ms	remaining: 970ms
154:	learn: 0.1074670	total: 178ms	remaining: 970ms
155:	learn: 0.1069390	total: 179ms	remaining: 969ms
156:	learn: 0.1063627	total: 180ms	remaining: 968ms
157:	learn: 0.1061244	total: 182ms	remaining: 968ms
158:	learn: 0.1055109	total: 183ms	remaining: 968ms
159:	learn: 0.1046262	total: 184ms	remaining: 966ms
160:	learn: 0.1043062	total: 185ms	remaining: 964ms
161:	learn: 0.1036220	total: 186ms	remaining: 963ms
162:	learn: 0.1028107	total: 188ms	remaining: 963ms
163:	learn: 0.1024058	total: 189ms	remaining: 961ms
164:	learn: 0.1018676	total: 190ms	remaining: 960ms
165:	learn: 0.1013521	total: 191ms	remaining: 958ms
166:	learn: 0.1011171	total: 192ms	remaining: 957ms
167:	learn: 0.1007034	total: 193ms	remaining: 955ms
168:	learn: 0.1001563	total: 194ms	remaining: 953ms
169:	learn: 0.0998054	total: 195ms	remaining: 951ms
170:	learn: 0.0994105	total: 196ms	remaining: 949ms
171:	learn: 0.0991428	total: 197ms	remaining: 947ms
172:	learn: 0.0986204	total: 198ms	remaining: 945ms
173:	learn: 0.0983758	total: 199ms	remaining: 943ms
174:	learn: 0.0982044	total: 200ms	remaining: 941ms
175:	learn: 0.0977567	total: 201ms	remaining: 940ms
176:	learn: 0.0972585	total: 202ms	remaining: 940ms
177:	learn: 0.0966900	total: 203ms	remaining: 938ms
178:	learn: 0.0961481	total: 204ms	remaining: 937ms
179:	learn: 0.0954159	total: 205ms	remaining: 935ms
180:	learn: 0.0950720	total: 206ms	remaining: 934ms
181:	learn: 0.0945468	total: 207ms	remaining: 932ms
182:	learn: 0.0942873	total: 208ms	remaining: 930ms
183:	learn: 0.0938351	total: 210ms	remaining: 930ms
184:	learn: 0.0934656	total: 211ms	remaining: 929ms
185:	learn: 0.0931280	total: 212ms	remaining: 927ms
186:	learn: 0.0924116	total: 213ms	remaining: 925ms
187:	learn: 0.0919619	total: 214ms	remaining: 924ms
188:	learn: 0.0911955	total: 215ms	remaining: 922ms
189:	learn: 0.0905559	total: 216ms	remaining: 921ms
190:	learn: 0.0903865	total: 218ms	remaining: 922ms
191:	learn: 0.0901126	total: 219ms	remaining: 923ms
192:	learn: 0.0895241	total: 221ms	remaining: 923ms
193:	learn: 0.0891870	total: 222ms	remaining: 921ms
194:	learn: 0.0887400	total: 223ms	remaining: 920ms
195:	learn: 0.0883415	total: 224ms	remaining: 918ms
196:	learn: 0.0880638	total: 225ms	remaining: 916ms
197:	learn: 0.0876470	total: 226ms	remaining: 914ms
198:	learn: 0.0875640	total: 227ms	remaining: 912ms
199:	learn: 0.0871566	total: 228ms	remaining: 911ms
200:	learn: 0.0867434	total: 229ms	remaining: 909ms
201:	learn: 0.0864000	total: 230ms	remaining: 907ms
202:	learn: 0.0861046	total: 231ms	remaining: 906ms
203:	learn: 0.0858163	total: 232ms	remaining: 905ms
204:	learn: 0.0853129	total: 233ms	remaining: 904ms
205:	learn: 0.0847667	total: 234ms	remaining: 902ms
206:	learn: 0.0845178	total: 235ms	remaining: 901ms
207:	learn: 0.0843373	total: 236ms	remaining: 900ms
208:	learn: 0.0837251	total: 238ms	remaining: 899ms
209:	learn: 0.0835813	total: 239ms	remaining: 897ms
210:	learn: 0.0834226	total: 240ms	remaining: 896ms
211:	learn: 0.0830743	total: 240ms	remaining: 893ms
212:	learn: 0.0826652	total: 241ms	remaining: 891ms
213:	learn: 0.0824265	total: 242ms	remaining: 890ms
214:	learn: 0.0820348	total: 243ms	remaining: 888ms
215:	learn: 0.0817420	total: 244ms	remaining: 887ms
216:	learn: 0.0814244	total: 245ms	remaining: 885ms
217:	learn: 0.0813267	total: 246ms	remaining: 884ms
218:	learn: 0.0809242	total: 248ms	remaining: 883ms
219:	learn: 0.0806108	total: 249ms	remaining: 882ms
220:	learn: 0.0804391	total: 250ms	remaining: 881ms
221:	learn: 0.0798872	total: 251ms	remaining: 879ms
222:	learn: 0.0797438	total: 252ms	remaining: 878ms
223:	learn: 0.0795864	total: 253ms	remaining: 876ms
224:	learn: 0.0791766	total: 254ms	remaining: 874ms
225:	learn: 0.0791056	total: 255ms	remaining: 873ms
226:	learn: 0.0789685	total: 256ms	remaining: 872ms
227:	learn: 0.0787194	total: 257ms	remaining: 870ms
228:	learn: 0.0786575	total: 258ms	remaining: 869ms
229:	learn: 0.0781860	total: 259ms	remaining: 867ms
230:	learn: 0.0776920	total: 260ms	remaining: 866ms
231:	learn: 0.0772813	total: 261ms	remaining: 864ms
232:	learn: 0.0771776	total: 262ms	remaining: 863ms
233:	learn: 0.0768045	total: 263ms	remaining: 862ms
234:	learn: 0.0763760	total: 265ms	remaining: 861ms
235:	learn: 0.0759456	total: 266ms	remaining: 860ms
236:	learn: 0.0758923	total: 266ms	remaining: 857ms
237:	learn: 0.0756218	total: 267ms	remaining: 855ms
238:	learn: 0.0755731	total: 268ms	remaining: 853ms
239:	learn: 0.0753972	total: 269ms	remaining: 851ms
240:	learn: 0.0750655	total: 270ms	remaining: 850ms
241:	learn: 0.0749152	total: 271ms	remaining: 848ms
242:	learn: 0.0747858	total: 272ms	remaining: 847ms
243:	learn: 0.0746514	total: 273ms	remaining: 845ms
244:	learn: 0.0742326	total: 274ms	remaining: 844ms
245:	learn: 0.0739047	total: 275ms	remaining: 843ms
246:	learn: 0.0735343	total: 276ms	remaining: 842ms
247:	learn: 0.0731252	total: 277ms	remaining: 841ms
248:	learn: 0.0730786	total: 278ms	remaining: 839ms
249:	learn: 0.0727882	total: 279ms	remaining: 838ms
250:	learn: 0.0723234	total: 280ms	remaining: 836ms
251:	learn: 0.0722714	total: 281ms	remaining: 834ms
252:	learn: 0.0722083	total: 282ms	remaining: 833ms
253:	learn: 0.0718062	total: 283ms	remaining: 831ms
254:	learn: 0.0714851	total: 284ms	remaining: 830ms
255:	learn: 0.0712372	total: 285ms	remaining: 829ms
256:	learn: 0.0708513	total: 286ms	remaining: 827ms
257:	learn: 0.0707938	total: 287ms	remaining: 826ms
258:	learn: 0.0706451	total: 288ms	remaining: 824ms
259:	learn: 0.0700631	total: 289ms	remaining: 822ms
260:	learn: 0.0696762	total: 290ms	remaining: 821ms
261:	learn: 0.0691502	total: 291ms	remaining: 820ms
262:	learn: 0.0685979	total: 292ms	remaining: 818ms
263:	learn: 0.0685437	total: 293ms	remaining: 818ms
264:	learn: 0.0681080	total: 295ms	remaining: 817ms
265:	learn: 0.0678235	total: 295ms	remaining: 815ms
266:	learn: 0.0674199	total: 296ms	remaining: 814ms
267:	learn: 0.0673664	total: 297ms	remaining: 812ms
268:	learn: 0.0669320	total: 298ms	remaining: 811ms
269:	learn: 0.0667791	total: 299ms	remaining: 810ms
270:	learn: 0.0665365	total: 301ms	remaining: 808ms
271:	learn: 0.0661170	total: 302ms	remaining: 807ms
272:	learn: 0.0657950	total: 303ms	remaining: 806ms
273:	learn: 0.0656462	total: 304ms	remaining: 804ms
274:	learn: 0.0653050	total: 305ms	remaining: 803ms
275:	learn: 0.0649716	total: 306ms	remaining: 802ms
276:	learn: 0.0649014	total: 307ms	remaining: 801ms
277:	learn: 0.0648510	total: 308ms	remaining: 799ms
278:	learn: 0.0645123	total: 309ms	remaining: 798ms
279:	learn: 0.0642592	total: 310ms	remaining: 797ms
280:	learn: 0.0639196	total: 311ms	remaining: 796ms
281:	learn: 0.0635486	total: 312ms	remaining: 795ms
282:	learn: 0.0635120	total: 313ms	remaining: 793ms
283:	learn: 0.0633181	total: 314ms	remaining: 792ms
284:	learn: 0.0631812	total: 315ms	remaining: 790ms
285:	learn: 0.0628621	total: 316ms	remaining: 789ms
286:	learn: 0.0625310	total: 317ms	remaining: 788ms
287:	learn: 0.0624856	total: 318ms	remaining: 786ms
288:	learn: 0.0621726	total: 319ms	remaining: 785ms
289:	learn: 0.0618569	total: 320ms	remaining: 783ms
290:	learn: 0.0615724	total: 321ms	remaining: 782ms
291:	learn: 0.0613483	total: 322ms	remaining: 781ms
292:	learn: 0.0612175	total: 323ms	remaining: 780ms
293:	learn: 0.0609251	total: 324ms	remaining: 779ms
294:	learn: 0.0605034	total: 326ms	remaining: 778ms
295:	learn: 0.0603767	total: 327ms	remaining: 777ms
296:	learn: 0.0603334	total: 328ms	remaining: 775ms
297:	learn: 0.0602560	total: 329ms	remaining: 774ms
298:	learn: 0.0598914	total: 330ms	remaining: 773ms
299:	learn: 0.0595649	total: 331ms	remaining: 772ms
300:	learn: 0.0594955	total: 332ms	remaining: 771ms
301:	learn: 0.0592781	total: 333ms	remaining: 769ms
302:	learn: 0.0589611	total: 334ms	remaining: 768ms
303:	learn: 0.0588126	total: 335ms	remaining: 767ms
304:	learn: 0.0584170	total: 336ms	remaining: 765ms
305:	learn: 0.0583729	total: 337ms	remaining: 764ms
306:	learn: 0.0581847	total: 338ms	remaining: 763ms
307:	learn: 0.0577992	total: 339ms	remaining: 762ms
308:	learn: 0.0575255	total: 341ms	remaining: 762ms
309:	learn: 0.0574827	total: 342ms	remaining: 761ms
310:	learn: 0.0571549	total: 343ms	remaining: 760ms
311:	learn: 0.0568549	total: 344ms	remaining: 759ms
312:	learn: 0.0566972	total: 345ms	remaining: 758ms
313:	learn: 0.0565432	total: 346ms	remaining: 757ms
314:	learn: 0.0563074	total: 348ms	remaining: 756ms
315:	learn: 0.0559391	total: 349ms	remaining: 755ms
316:	learn: 0.0559028	total: 350ms	remaining: 755ms
317:	learn: 0.0557935	total: 352ms	remaining: 754ms
318:	learn: 0.0555666	total: 353ms	remaining: 754ms
319:	learn: 0.0552640	total: 355ms	remaining: 754ms
320:	learn: 0.0548962	total: 356ms	remaining: 754ms
321:	learn: 0.0545450	total: 358ms	remaining: 753ms
322:	learn: 0.0544023	total: 359ms	remaining: 753ms
323:	learn: 0.0541023	total: 361ms	remaining: 752ms
324:	learn: 0.0538667	total: 362ms	remaining: 751ms
325:	learn: 0.0536141	total: 363ms	remaining: 750ms
326:	learn: 0.0534745	total: 364ms	remaining: 750ms
327:	learn: 0.0532450	total: 366ms	remaining: 749ms
328:	learn: 0.0529449	total: 367ms	remaining: 749ms
329:	learn: 0.0528448	total: 368ms	remaining: 747ms
330:	learn: 0.0526374	total: 369ms	remaining: 746ms
331:	learn: 0.0526035	total: 371ms	remaining: 746ms
332:	learn: 0.0523793	total: 372ms	remaining: 745ms
333:	learn: 0.0519654	total: 373ms	remaining: 744ms
334:	learn: 0.0517473	total: 375ms	remaining: 744ms
335:	learn: 0.0517147	total: 376ms	remaining: 743ms
336:	learn: 0.0514219	total: 377ms	remaining: 742ms
337:	learn: 0.0512298	total: 378ms	remaining: 741ms
338:	learn: 0.0508993	total: 379ms	remaining: 740ms
339:	learn: 0.0505149	total: 380ms	remaining: 738ms
340:	learn: 0.0503257	total: 381ms	remaining: 737ms
341:	learn: 0.0500865	total: 382ms	remaining: 736ms
342:	learn: 0.0498919	total: 383ms	remaining: 735ms
343:	learn: 0.0498271	total: 384ms	remaining: 733ms
344:	learn: 0.0496459	total: 386ms	remaining: 732ms
345:	learn: 0.0493917	total: 387ms	remaining: 732ms
346:	learn: 0.0492209	total: 388ms	remaining: 731ms
347:	learn: 0.0490584	total: 390ms	remaining: 730ms
348:	learn: 0.0488270	total: 391ms	remaining: 728ms
349:	learn: 0.0487341	total: 392ms	remaining: 727ms
350:	learn: 0.0485101	total: 393ms	remaining: 726ms
351:	learn: 0.0482073	total: 394ms	remaining: 725ms
352:	learn: 0.0481750	total: 395ms	remaining: 724ms
353:	learn: 0.0479465	total: 396ms	remaining: 723ms
354:	learn: 0.0478065	total: 397ms	remaining: 721ms
355:	learn: 0.0475049	total: 398ms	remaining: 720ms
356:	learn: 0.0473324	total: 399ms	remaining: 719ms
357:	learn: 0.0472810	total: 400ms	remaining: 717ms
358:	learn: 0.0472236	total: 401ms	remaining: 716ms
359:	learn: 0.0468826	total: 403ms	remaining: 716ms
360:	learn: 0.0466918	total: 407ms	remaining: 720ms
361:	learn: 0.0465309	total: 408ms	remaining: 720ms
362:	learn: 0.0464957	total: 410ms	remaining: 719ms
363:	learn: 0.0461726	total: 411ms	remaining: 718ms
364:	learn: 0.0458157	total: 413ms	remaining: 718ms
365:	learn: 0.0454927	total: 414ms	remaining: 717ms
366:	learn: 0.0454112	total: 415ms	remaining: 715ms
367:	learn: 0.0451257	total: 416ms	remaining: 714ms
368:	learn: 0.0448849	total: 417ms	remaining: 713ms
369:	learn: 0.0446511	total: 418ms	remaining: 712ms
370:	learn: 0.0446232	total: 419ms	remaining: 711ms
371:	learn: 0.0444889	total: 421ms	remaining: 710ms
372:	learn: 0.0441806	total: 422ms	remaining: 709ms
373:	learn: 0.0441321	total: 423ms	remaining: 708ms
374:	learn: 0.0438236	total: 424ms	remaining: 706ms
375:	learn: 0.0435199	total: 425ms	remaining: 705ms
376:	learn: 0.0434943	total: 426ms	remaining: 703ms
377:	learn: 0.0431699	total: 427ms	remaining: 702ms
378:	learn: 0.0430388	total: 428ms	remaining: 701ms

In [46]:
#saving the models

import pickle



filename = 'XGB_reg_basic.sav'
pickle.dump(XGB_reg_basic, open(filename, 'wb'))

filename = 'LGBM_reg_basic.sav'
pickle.dump(LGBM_reg_basic, open(filename, 'wb'))

filename = 'model_CB_basic.sav'
pickle.dump(model_CB_basic, open(filename, 'wb'))


filename = 'XGB_reg_all.sav'
pickle.dump(XGB_reg_all, open(filename, 'wb'))

filename = 'LGBM_reg_all.sav'
pickle.dump(LGBM_reg_all, open(filename, 'wb'))

filename = 'model_CB_all.sav'
pickle.dump(model_CB_all, open(filename, 'wb'))


filename = 'XGB_reg_all_plus_plus.sav'
pickle.dump(XGB_reg_all_plus_plus, open(filename, 'wb'))

filename = 'LGBM_reg_all_plus_plus.sav'
pickle.dump(LGBM_reg_all_plus_plus, open(filename, 'wb'))

filename = 'model_CB_all_plus_plus.sav'
pickle.dump(model_CB_all_plus_plus, open(filename, 'wb'))