In [1]:
import pandas as pd

df = pd.read_excel('../Example_database_withoutrois.xlsx') 
df.head()

,Identifiers,age,sex,education,education_group,language,fluency_score,handedness,nb_language,hearing,...,anxiety_score,smoking,alcohol,poly_pharm5,poly_pharm10,physical_activity,social_life,cognitive_activities,nutrition_score,sleep_deprivation
0,4509950,70.3,1.0,21.0,4.0,1.0,18.0,0.0,2,0.0,...,6.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
1,7424803,78.4,1.0,14.0,2.0,1.0,19.0,0.0,2,1.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,7874568,74.5,0.0,18.0,4.0,1.0,17.0,0.0,2,0.0,...,3.0,0.0,0.0,NaN,NaN,0.0,1.0,0.0,0.0,1.0
3,3865361,73.3,1.0,14.0,2.0,1.0,17.0,0.0,2,0.0,...,4.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0
4,6841569,73.8,1.0,15.0,3.0,1.0,24.0,0.0,1,0.0,...,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0

From this function we can see that we have null values in some columns, and since we are in the exploratory phase we need clean and complete data, in order to understand relationships between columns, so now we gonna drop Na values

In [2]:
# List of column names you want to keep
basic_columns = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'risk_dementia']
all_columns = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'handedness','nb_language','hearing','moca','ravlt_imm','ravlt_delay', 'logic_imm', 'logic_delay', 'risk_dementia']
all_columns_plus_plus = ['Identifiers', 'age', 'sex', 'education', 'language', 'fluency_score', 'neurocog_age_flu_weight', 'handedness','nb_language','hearing','moca','ravlt_imm','ravlt_delay', 'logic_imm', 'logic_delay', 'hist_demence_fam', 'hist_demence_parent', 'living_alone', 'income', 'retired','stroke', 'tbi', 'hta', 'diab_type2', 'obesity', 'depression', 'anxiety', 'smoking', 'alcohol','poly_pharm5', 'physical_activity', 'social_life','cognitive_activities','nutrition_score','sleep_deprivation', 'risk_dementia']

# Select only those columns
df_basic = df[basic_columns]
df_all = df[all_columns]
df_all_plus_plus = df[all_columns_plus_plus]

In [3]:
df_basic = df_basic.dropna()
df_all = df_all.dropna()
df_all_plus_plus = df_all_plus_plus.dropna()


df_basic.describe()
df_all.describe()
df_all_plus_plus.describe()

,age,sex,education,language,fluency_score,neurocog_age_flu_weight,handedness,nb_language,hearing,moca,...,anxiety,smoking,alcohol,poly_pharm5,physical_activity,social_life,cognitive_activities,nutrition_score,sleep_deprivation,risk_dementia
count,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,...,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000,668.000000
mean,72.095808,0.543413,15.619012,0.185629,18.995509,74.731080,0.104790,1.959581,0.040419,23.869760,...,0.059880,0.426647,0.115269,0.630240,0.103293,0.464072,0.100299,0.368263,0.113772,0.416168
std,6.695071,0.498485,3.442239,0.389098,6.296638,11.202246,0.306513,1.051813,0.197088,4.258807,...,0.237443,0.494961,0.319586,0.483101,0.304570,0.499081,0.300624,0.482695,0.317773,0.344817
min,57.400000,0.000000,5.000000,0.000000,0.000000,48.941804,0.000000,1.000000,0.000000,9.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,66.600000,0.000000,13.000000,0.000000,15.000000,66.374971,0.000000,1.000000,0.000000,21.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,72.250000,1.000000,15.250000,0.000000,19.000000,74.357982,0.000000,2.000000,0.000000,25.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000
75%,77.000000,1.000000,18.000000,0.000000,23.000000,82.964218,0.000000,2.000000,0.000000,27.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.500000
max,89.700000,1.000000,30.000000,1.000000,37.000000,104.935177,1.000000,6.000000,1.000000,30.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

We can see that we droped the half of our data, in fact that will impact the performance of our models, but in a first place to get to know the correlations and the right columns to choose this is the only way. Once this is done we can get back to drop non necessary columns and use only target columns with no null values

In [4]:
df_basic = df_basic.drop('Identifiers', axis=1)
df_all = df_all.drop('Identifiers', axis=1)
df_all_plus_plus = df_all_plus_plus.drop('Identifiers', axis=1)

In [5]:
corr_all = df_all.corr()
corr_basic = df_basic.corr()
corr_all_plus_plus = df_all_plus_plus.corr()

In [6]:
correlation_all = pd.DataFrame(corr_all)
correlation_basic = pd.DataFrame(corr_basic)
correlation_all_plus_plus = pd.DataFrame(corr_all_plus_plus)

In [7]:
new_correlation_all = abs(correlation_all['risk_dementia'])
new_correlation_basic = abs(correlation_basic['risk_dementia'])
new_correlation_all_plus_plus = abs(correlation_all_plus_plus['risk_dementia'])

In [8]:
new_correlation_all_plus_plus = new_correlation_all_plus_plus.sort_values(ascending=False)
new_correlation_all_plus_plus

risk_dementia              1.000000
moca                       0.740477
ravlt_imm                  0.705494
logic_delay                0.691962
ravlt_delay                0.690883
logic_imm                  0.665986
neurocog_age_flu_weight    0.645682
fluency_score              0.582974
sex                        0.270994
age                        0.266665
living_alone               0.194745
language                   0.157613
smoking                    0.106360
poly_pharm5                0.106142
stroke                     0.103356
hta                        0.096360
retired                    0.090557
education                  0.081895
anxiety                    0.079716
handedness                 0.069058
cognitive_activities       0.066773
alcohol                    0.055031
nutrition_score            0.052940
hearing                    0.049935
hist_demence_parent        0.040981
social_life                0.039308
physical_activity          0.038767
nb_language                0.036115
income                     0.032813
obesity                    0.029083
hist_demence_fam           0.027208
depression                 0.025038
diab_type2                 0.024340
sleep_deprivation          0.022285
tbi                        0.003321
Name: risk_dementia, dtype: float64

In [9]:
new_correlation_basic = new_correlation_basic.sort_values(ascending=False)
new_correlation_basic

risk_dementia              1.000000
neurocog_age_flu_weight    0.441492
fluency_score              0.430340
language                   0.295780
sex                        0.243538
age                        0.078143
education                  0.050029
Name: risk_dementia, dtype: float64

In [10]:
new_correlation_all = new_correlation_all.sort_values(ascending=False)
new_correlation_all

risk_dementia              1.000000
moca                       0.760370
logic_delay                0.711729
ravlt_delay                0.701343
ravlt_imm                  0.700302
logic_imm                  0.680111
neurocog_age_flu_weight    0.637735
fluency_score              0.548499
language                   0.285432
age                        0.254625
sex                        0.242259
education                  0.076475
handedness                 0.060250
nb_language                0.041548
hearing                    0.023071
Name: risk_dementia, dtype: float64

In [11]:
new_correlation_all_plus_plus = pd.DataFrame(new_correlation_all_plus_plus)
new_correlation_all_plus_plus['column_name'] = new_correlation_all_plus_plus.index
new_correlation_all_plus_plus.reset_index(drop=True, inplace=True)

In [12]:
new_correlation_basic = pd.DataFrame(new_correlation_basic)
new_correlation_basic['column_name'] = new_correlation_basic.index
new_correlation_basic.reset_index(drop=True, inplace=True)

In [13]:
new_correlation_all = pd.DataFrame(new_correlation_all)
new_correlation_all['column_name'] = new_correlation_all.index
new_correlation_all.reset_index(drop=True, inplace=True)

In [14]:
relevant_columns_basic = new_correlation_basic.loc[new_correlation_basic['risk_dementia'] > 0, 'column_name']
relevant_columns_basic = relevant_columns_basic[relevant_columns_basic != 'risk_dementia']
relevant_columns_basic = relevant_columns_basic[relevant_columns_basic != 'risk_dementia']
print(relevant_columns_basic)


relevant_columns_all = new_correlation_all.loc[new_correlation_all['risk_dementia'] > 0, 'column_name']
relevant_columns_all = relevant_columns_all[relevant_columns_all != 'risk_dementia']
relevant_columns_all = relevant_columns_all[relevant_columns_all != 'risk_dementia']
print(relevant_columns_all)


relevant_columns_all_plus_plus = new_correlation_all_plus_plus.loc[new_correlation_all_plus_plus['risk_dementia'] > 0, 'column_name']
relevant_columns_all_plus_plus = relevant_columns_all_plus_plus[relevant_columns_all_plus_plus != 'risk_dementia']
relevant_columns_all_plus_plus = relevant_columns_all_plus_plus[relevant_columns_all_plus_plus != 'risk_dementia']
print(relevant_columns_all_plus_plus)

1    neurocog_age_flu_weight
2              fluency_score
3                   language
4                        sex
5                        age
6                  education
Name: column_name, dtype: object
1                        moca
2                 logic_delay
3                 ravlt_delay
4                   ravlt_imm
5                   logic_imm
6     neurocog_age_flu_weight
7               fluency_score
8                    language
9                         age
10                        sex
11                  education
12                 handedness
13                nb_language
14                    hearing
Name: column_name, dtype: object
1                        moca
2                   ravlt_imm
3                 logic_delay
4                 ravlt_delay
5                   logic_imm
6     neurocog_age_flu_weight
7               fluency_score
8                         sex
9                         age
10               living_alone
11                   language
12                    smoking
13                poly_pharm5
14                     stroke
15                        hta
16                    retired
17                  education
18                    anxiety
19                 handedness
20       cognitive_activities
21                    alcohol
22            nutrition_score
23                    hearing
24        hist_demence_parent
25                social_life
26          physical_activity
27                nb_language
28                     income
29                    obesity
30           hist_demence_fam
31                 depression
32                 diab_type2
33          sleep_deprivation
34                        tbi
Name: column_name, dtype: object

In this part we will choose the relevent columns for our model, these columns should have a correlation value higher than 50%

In [15]:
from sklearn.metrics import median_absolute_error, mean_absolute_error, mean_squared_error
import numpy as np
def print_error_metrics(y_true: np.array, y_pred: np.array) -> None:
    """
    Function to compute the mean absolute error, mean squared error, and median absolute error and print to screen
    
    Inputs:
        y_true -> array containing actual dependant variable
        y_pred -> array containing model predictions
    """
    mee = median_absolute_error(y_true,y_pred)
    mae = mean_absolute_error(y_true,y_pred)
    mse = mean_squared_error(y_true,y_pred)
    print("The median absolute error is: {:.2f}".format(mee))
    print("The mean absolute error is: {:.2f}".format(mae))
    print("The root mean squared error is: {:.2f}".format(np.sqrt(mse)))

In [16]:
def pred_to_proba(y_pred):
    predictions = []
    for value in y_pred:
        value = int(value*100)
        if value < 0 :
            value = 0
        elif value > 100 :
            value = 100
        else:
            pass
        predictions.append(value/100)
    
    return predictions

In [17]:
#!pip install lightgbm==3.3.5

In [18]:
#pip install xgboost

In [19]:
#!pip install catboost

In [20]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor 
import catboost as cb

def train_best_reg_models(df, relevant_columns):
    X_train, X_test, y_train, y_test = train_test_split(df[relevant_columns],df["risk_dementia"],test_size=0.8)
    XGB_reg = XGBRegressor().fit(X_train, y_train)
    y_predict = pred_to_proba(XGB_reg.predict(X_test))
    print("Error metrics for XGBoost regression model :")
    print_error_metrics(y_test, y_predict)

    LGBM_reg = LGBMRegressor(metric='rmse')
    LGBM_reg.fit(X_train, y_train)
    y_predict = pred_to_proba(LGBM_reg.predict(X_test))
    print("Error metrics for LightGBM regression model :")
    print_error_metrics(y_test, y_predict)

    model_CB = cb.CatBoostRegressor()
    model_CB.fit(X_train, y_train)
    y_predict = pred_to_proba(model_CB.predict(X_test))
    print("Error metrics for Cat boost regression model :")
    print_error_metrics(y_test, y_predict)
    return XGB_reg, LGBM_reg, model_CB

In [21]:
XGB_reg_basic, LGBM_reg_basic, model_CB_basic = train_best_reg_models(df_basic, relevant_columns_basic)

Error metrics for XGBoost regression model :
The median absolute error is: 0.19
The mean absolute error is: 0.24
The root mean squared error is: 0.32
Error metrics for LightGBM regression model :
The median absolute error is: 0.22
The mean absolute error is: 0.25
The root mean squared error is: 0.31
Learning rate set to 0.032044
0:	learn: 0.3573467	total: 142ms	remaining: 2m 22s
1:	learn: 0.3542480	total: 143ms	remaining: 1m 11s
2:	learn: 0.3509842	total: 144ms	remaining: 47.9s
3:	learn: 0.3480148	total: 145ms	remaining: 36s
4:	learn: 0.3452779	total: 145ms	remaining: 28.9s
5:	learn: 0.3421851	total: 146ms	remaining: 24.1s
6:	learn: 0.3398231	total: 146ms	remaining: 20.8s
7:	learn: 0.3368827	total: 147ms	remaining: 18.2s
8:	learn: 0.3341569	total: 147ms	remaining: 16.2s
9:	learn: 0.3319121	total: 148ms	remaining: 14.6s
10:	learn: 0.3296047	total: 149ms	remaining: 13.4s
11:	learn: 0.3271568	total: 149ms	remaining: 12.3s
12:	learn: 0.3247816	total: 150ms	remaining: 11.4s
13:	learn: 0.3226818	total: 150ms	remaining: 10.6s
14:	learn: 0.3208155	total: 151ms	remaining: 9.89s
15:	learn: 0.3188282	total: 151ms	remaining: 9.3s
16:	learn: 0.3164958	total: 152ms	remaining: 8.79s
17:	learn: 0.3143347	total: 153ms	remaining: 8.32s
18:	learn: 0.3122449	total: 153ms	remaining: 7.91s
19:	learn: 0.3104247	total: 154ms	remaining: 7.53s
20:	learn: 0.3088744	total: 154ms	remaining: 7.19s
21:	learn: 0.3067185	total: 156ms	remaining: 6.91s
22:	learn: 0.3057231	total: 156ms	remaining: 6.63s
23:	learn: 0.3042651	total: 156ms	remaining: 6.36s
24:	learn: 0.3027294	total: 157ms	remaining: 6.12s
25:	learn: 0.3013110	total: 158ms	remaining: 5.9s
26:	learn: 0.2997143	total: 158ms	remaining: 5.7s
27:	learn: 0.2981616	total: 159ms	remaining: 5.51s
28:	learn: 0.2963833	total: 159ms	remaining: 5.33s
29:	learn: 0.2950787	total: 160ms	remaining: 5.16s
30:	learn: 0.2938464	total: 160ms	remaining: 5.01s
31:	learn: 0.2925593	total: 161ms	remaining: 4.86s
32:	learn: 0.2913849	total: 162ms	remaining: 4.73s
33:	learn: 0.2902446	total: 162ms	remaining: 4.61s
34:	learn: 0.2893803	total: 163ms	remaining: 4.48s
35:	learn: 0.2882580	total: 163ms	remaining: 4.37s
36:	learn: 0.2870494	total: 164ms	remaining: 4.26s
37:	learn: 0.2860321	total: 164ms	remaining: 4.16s
38:	learn: 0.2849899	total: 165ms	remaining: 4.06s
39:	learn: 0.2843277	total: 165ms	remaining: 3.97s
40:	learn: 0.2832635	total: 166ms	remaining: 3.88s
41:	learn: 0.2820938	total: 166ms	remaining: 3.8s
42:	learn: 0.2810629	total: 167ms	remaining: 3.72s
43:	learn: 0.2798858	total: 168ms	remaining: 3.64s
44:	learn: 0.2789945	total: 168ms	remaining: 3.57s
45:	learn: 0.2784301	total: 169ms	remaining: 3.5s
46:	learn: 0.2775085	total: 169ms	remaining: 3.43s
47:	learn: 0.2767222	total: 170ms	remaining: 3.38s
48:	learn: 0.2759302	total: 171ms	remaining: 3.32s
49:	learn: 0.2745854	total: 172ms	remaining: 3.26s
50:	learn: 0.2733629	total: 173ms	remaining: 3.21s
51:	learn: 0.2723025	total: 173ms	remaining: 3.16s
52:	learn: 0.2714299	total: 174ms	remaining: 3.1s
53:	learn: 0.2704231	total: 174ms	remaining: 3.05s
54:	learn: 0.2697941	total: 175ms	remaining: 3s
55:	learn: 0.2690678	total: 175ms	remaining: 2.96s
56:	learn: 0.2682870	total: 176ms	remaining: 2.91s
57:	learn: 0.2671047	total: 176ms	remaining: 2.87s
58:	learn: 0.2663340	total: 177ms	remaining: 2.82s
59:	learn: 0.2653557	total: 178ms	remaining: 2.78s
60:	learn: 0.2645337	total: 178ms	remaining: 2.74s
61:	learn: 0.2641677	total: 179ms	remaining: 2.71s
62:	learn: 0.2634834	total: 180ms	remaining: 2.67s
63:	learn: 0.2627915	total: 180ms	remaining: 2.63s
64:	learn: 0.2623536	total: 181ms	remaining: 2.6s
65:	learn: 0.2617056	total: 181ms	remaining: 2.56s
66:	learn: 0.2608149	total: 182ms	remaining: 2.53s
67:	learn: 0.2601270	total: 182ms	remaining: 2.5s
68:	learn: 0.2595074	total: 183ms	remaining: 2.47s
69:	learn: 0.2588226	total: 183ms	remaining: 2.44s
70:	learn: 0.2579610	total: 184ms	remaining: 2.41s
71:	learn: 0.2572973	total: 185ms	remaining: 2.38s
72:	learn: 0.2567823	total: 185ms	remaining: 2.35s
73:	learn: 0.2562452	total: 186ms	remaining: 2.33s
74:	learn: 0.2549379	total: 187ms	remaining: 2.3s
75:	learn: 0.2541971	total: 187ms	remaining: 2.28s
76:	learn: 0.2536261	total: 188ms	remaining: 2.25s
77:	learn: 0.2531572	total: 189ms	remaining: 2.23s
78:	learn: 0.2526815	total: 189ms	remaining: 2.21s
79:	learn: 0.2522224	total: 190ms	remaining: 2.18s
80:	learn: 0.2518622	total: 190ms	remaining: 2.16s
81:	learn: 0.2513614	total: 191ms	remaining: 2.14s
82:	learn: 0.2505185	total: 191ms	remaining: 2.11s
83:	learn: 0.2497452	total: 192ms	remaining: 2.09s
84:	learn: 0.2493085	total: 192ms	remaining: 2.07s
85:	learn: 0.2486171	total: 193ms	remaining: 2.05s
86:	learn: 0.2482002	total: 194ms	remaining: 2.03s
87:	learn: 0.2476027	total: 194ms	remaining: 2.01s
88:	learn: 0.2471860	total: 195ms	remaining: 1.99s
89:	learn: 0.2466091	total: 195ms	remaining: 1.97s
90:	learn: 0.2458914	total: 196ms	remaining: 1.96s
91:	learn: 0.2451844	total: 196ms	remaining: 1.94s
92:	learn: 0.2444362	total: 197ms	remaining: 1.92s
93:	learn: 0.2440396	total: 198ms	remaining: 1.9s
94:	learn: 0.2434334	total: 198ms	remaining: 1.89s
95:	learn: 0.2426302	total: 199ms	remaining: 1.87s
96:	learn: 0.2420360	total: 199ms	remaining: 1.85s
97:	learn: 0.2415981	total: 200ms	remaining: 1.84s
98:	learn: 0.2410925	total: 201ms	remaining: 1.82s
99:	learn: 0.2406090	total: 201ms	remaining: 1.81s
100:	learn: 0.2402342	total: 202ms	remaining: 1.79s
101:	learn: 0.2399346	total: 202ms	remaining: 1.78s
102:	learn: 0.2395234	total: 203ms	remaining: 1.76s
103:	learn: 0.2386298	total: 203ms	remaining: 1.75s
104:	learn: 0.2382361	total: 204ms	remaining: 1.74s
105:	learn: 0.2375080	total: 204ms	remaining: 1.72s
106:	learn: 0.2370216	total: 205ms	remaining: 1.71s
107:	learn: 0.2368571	total: 205ms	remaining: 1.69s
108:	learn: 0.2364672	total: 206ms	remaining: 1.68s
109:	learn: 0.2360644	total: 206ms	remaining: 1.67s
110:	learn: 0.2354205	total: 207ms	remaining: 1.66s
111:	learn: 0.2348589	total: 207ms	remaining: 1.64s
112:	learn: 0.2343865	total: 208ms	remaining: 1.63s
113:	learn: 0.2338787	total: 209ms	remaining: 1.62s
114:	learn: 0.2333774	total: 209ms	remaining: 1.61s
115:	learn: 0.2330973	total: 210ms	remaining: 1.6s
116:	learn: 0.2327190	total: 210ms	remaining: 1.59s
117:	learn: 0.2323851	total: 211ms	remaining: 1.57s
118:	learn: 0.2320645	total: 211ms	remaining: 1.56s
119:	learn: 0.2317344	total: 212ms	remaining: 1.55s
120:	learn: 0.2312427	total: 212ms	remaining: 1.54s
121:	learn: 0.2310778	total: 213ms	remaining: 1.53s
122:	learn: 0.2303587	total: 213ms	remaining: 1.52s
123:	learn: 0.2297870	total: 214ms	remaining: 1.51s
124:	learn: 0.2292428	total: 215ms	remaining: 1.5s
125:	learn: 0.2287513	total: 216ms	remaining: 1.5s
126:	learn: 0.2285084	total: 216ms	remaining: 1.49s
127:	learn: 0.2279583	total: 217ms	remaining: 1.48s
128:	learn: 0.2276448	total: 218ms	remaining: 1.47s
129:	learn: 0.2271837	total: 218ms	remaining: 1.46s
130:	learn: 0.2268443	total: 219ms	remaining: 1.45s
131:	learn: 0.2263327	total: 219ms	remaining: 1.44s
132:	learn: 0.2259807	total: 220ms	remaining: 1.43s
133:	learn: 0.2253204	total: 220ms	remaining: 1.42s
134:	learn: 0.2250873	total: 221ms	remaining: 1.41s
135:	learn: 0.2244237	total: 221ms	remaining: 1.41s
136:	learn: 0.2240736	total: 222ms	remaining: 1.4s
137:	learn: 0.2237500	total: 222ms	remaining: 1.39s
138:	learn: 0.2234878	total: 223ms	remaining: 1.38s
139:	learn: 0.2231953	total: 223ms	remaining: 1.37s
140:	learn: 0.2226218	total: 224ms	remaining: 1.36s
141:	learn: 0.2223541	total: 225ms	remaining: 1.36s
142:	learn: 0.2220003	total: 225ms	remaining: 1.35s
143:	learn: 0.2215146	total: 226ms	remaining: 1.34s
144:	learn: 0.2211021	total: 226ms	remaining: 1.33s
145:	learn: 0.2207463	total: 227ms	remaining: 1.32s
146:	learn: 0.2204125	total: 227ms	remaining: 1.32s
147:	learn: 0.2198381	total: 228ms	remaining: 1.31s
148:	learn: 0.2193469	total: 228ms	remaining: 1.3s
149:	learn: 0.2190803	total: 229ms	remaining: 1.3s
150:	learn: 0.2187104	total: 229ms	remaining: 1.29s
151:	learn: 0.2182129	total: 230ms	remaining: 1.28s
152:	learn: 0.2176247	total: 231ms	remaining: 1.28s
153:	learn: 0.2173148	total: 232ms	remaining: 1.27s
154:	learn: 0.2170034	total: 232ms	remaining: 1.27s
155:	learn: 0.2165362	total: 233ms	remaining: 1.26s
156:	learn: 0.2161320	total: 234ms	remaining: 1.25s
157:	learn: 0.2158756	total: 234ms	remaining: 1.25s
158:	learn: 0.2156887	total: 235ms	remaining: 1.24s
159:	learn: 0.2153909	total: 235ms	remaining: 1.24s
160:	learn: 0.2153016	total: 236ms	remaining: 1.23s
161:	learn: 0.2150009	total: 236ms	remaining: 1.22s
162:	learn: 0.2146920	total: 237ms	remaining: 1.21s
163:	learn: 0.2143947	total: 237ms	remaining: 1.21s
164:	learn: 0.2140350	total: 238ms	remaining: 1.2s
165:	learn: 0.2138261	total: 238ms	remaining: 1.2s
166:	learn: 0.2133027	total: 239ms	remaining: 1.19s
167:	learn: 0.2128306	total: 239ms	remaining: 1.18s
168:	learn: 0.2124962	total: 240ms	remaining: 1.18s
169:	learn: 0.2121806	total: 240ms	remaining: 1.17s
170:	learn: 0.2119489	total: 241ms	remaining: 1.17s
171:	learn: 0.2116011	total: 242ms	remaining: 1.16s
172:	learn: 0.2114014	total: 242ms	remaining: 1.16s
173:	learn: 0.2112022	total: 243ms	remaining: 1.15s
174:	learn: 0.2108722	total: 243ms	remaining: 1.15s
175:	learn: 0.2105786	total: 244ms	remaining: 1.14s
176:	learn: 0.2102735	total: 245ms	remaining: 1.14s
177:	learn: 0.2099635	total: 245ms	remaining: 1.13s
178:	learn: 0.2096219	total: 246ms	remaining: 1.13s
179:	learn: 0.2092375	total: 247ms	remaining: 1.12s
180:	learn: 0.2090030	total: 247ms	remaining: 1.12s
181:	learn: 0.2086020	total: 248ms	remaining: 1.11s
182:	learn: 0.2081289	total: 248ms	remaining: 1.11s
183:	learn: 0.2077605	total: 249ms	remaining: 1.1s
184:	learn: 0.2074875	total: 249ms	remaining: 1.1s
185:	learn: 0.2071299	total: 250ms	remaining: 1.09s
186:	learn: 0.2066305	total: 250ms	remaining: 1.09s
187:	learn: 0.2064147	total: 251ms	remaining: 1.08s
188:	learn: 0.2060840	total: 252ms	remaining: 1.08s
189:	learn: 0.2055508	total: 252ms	remaining: 1.07s
190:	learn: 0.2052228	total: 253ms	remaining: 1.07s
191:	learn: 0.2046816	total: 253ms	remaining: 1.07s
192:	learn: 0.2043953	total: 254ms	remaining: 1.06s
193:	learn: 0.2041342	total: 254ms	remaining: 1.06s
194:	learn: 0.2038481	total: 255ms	remaining: 1.05s
195:	learn: 0.2035479	total: 255ms	remaining: 1.05s
196:	learn: 0.2034136	total: 256ms	remaining: 1.04s
197:	learn: 0.2028679	total: 257ms	remaining: 1.04s
198:	learn: 0.2024066	total: 257ms	remaining: 1.03s
199:	learn: 0.2018967	total: 258ms	remaining: 1.03s
200:	learn: 0.2017185	total: 259ms	remaining: 1.03s
201:	learn: 0.2014920	total: 260ms	remaining: 1.03s
202:	learn: 0.2013013	total: 261ms	remaining: 1.02s
203:	learn: 0.2010021	total: 262ms	remaining: 1.02s
204:	learn: 0.2007889	total: 263ms	remaining: 1.02s
205:	learn: 0.2005749	total: 263ms	remaining: 1.01s
206:	learn: 0.2002122	total: 264ms	remaining: 1.01s
207:	learn: 0.1999053	total: 265ms	remaining: 1.01s
208:	learn: 0.1996588	total: 266ms	remaining: 1.01s
209:	learn: 0.1992350	total: 267ms	remaining: 1s
210:	learn: 0.1989782	total: 268ms	remaining: 1s
211:	learn: 0.1987774	total: 268ms	remaining: 998ms
212:	learn: 0.1985714	total: 269ms	remaining: 994ms
213:	learn: 0.1982107	total: 270ms	remaining: 990ms
214:	learn: 0.1975921	total: 271ms	remaining: 988ms
215:	learn: 0.1973570	total: 271ms	remaining: 984ms
216:	learn: 0.1971013	total: 272ms	remaining: 981ms
217:	learn: 0.1963124	total: 273ms	remaining: 978ms
218:	learn: 0.1960033	total: 273ms	remaining: 975ms
219:	learn: 0.1958584	total: 274ms	remaining: 972ms
220:	learn: 0.1956109	total: 275ms	remaining: 968ms
221:	learn: 0.1952719	total: 276ms	remaining: 966ms
222:	learn: 0.1949434	total: 276ms	remaining: 963ms
223:	learn: 0.1945627	total: 277ms	remaining: 961ms
224:	learn: 0.1943249	total: 278ms	remaining: 958ms
225:	learn: 0.1940868	total: 279ms	remaining: 954ms
226:	learn: 0.1937857	total: 279ms	remaining: 951ms
227:	learn: 0.1934775	total: 280ms	remaining: 947ms
228:	learn: 0.1933427	total: 280ms	remaining: 944ms
229:	learn: 0.1929839	total: 281ms	remaining: 940ms
230:	learn: 0.1926709	total: 281ms	remaining: 937ms
231:	learn: 0.1925335	total: 282ms	remaining: 933ms
232:	learn: 0.1922985	total: 282ms	remaining: 930ms
233:	learn: 0.1921703	total: 283ms	remaining: 927ms
234:	learn: 0.1919726	total: 284ms	remaining: 923ms
235:	learn: 0.1917502	total: 284ms	remaining: 920ms
236:	learn: 0.1915723	total: 285ms	remaining: 916ms
237:	learn: 0.1914392	total: 285ms	remaining: 913ms
238:	learn: 0.1912548	total: 286ms	remaining: 909ms
239:	learn: 0.1904444	total: 286ms	remaining: 906ms
240:	learn: 0.1903186	total: 287ms	remaining: 904ms
241:	learn: 0.1900691	total: 287ms	remaining: 900ms
242:	learn: 0.1896332	total: 288ms	remaining: 897ms
243:	learn: 0.1888119	total: 289ms	remaining: 894ms
244:	learn: 0.1885798	total: 289ms	remaining: 891ms
245:	learn: 0.1884608	total: 290ms	remaining: 888ms
246:	learn: 0.1882787	total: 290ms	remaining: 885ms
247:	learn: 0.1878782	total: 291ms	remaining: 883ms
248:	learn: 0.1876182	total: 292ms	remaining: 880ms
249:	learn: 0.1874972	total: 292ms	remaining: 877ms
250:	learn: 0.1869370	total: 293ms	remaining: 875ms
251:	learn: 0.1868161	total: 294ms	remaining: 872ms
252:	learn: 0.1866906	total: 294ms	remaining: 869ms
253:	learn: 0.1864657	total: 295ms	remaining: 866ms
254:	learn: 0.1860595	total: 296ms	remaining: 863ms
255:	learn: 0.1858622	total: 296ms	remaining: 861ms
256:	learn: 0.1857083	total: 297ms	remaining: 858ms
257:	learn: 0.1855361	total: 297ms	remaining: 855ms
258:	learn: 0.1854371	total: 298ms	remaining: 853ms
259:	learn: 0.1851917	total: 299ms	remaining: 850ms
260:	learn: 0.1850823	total: 299ms	remaining: 848ms
261:	learn: 0.1846787	total: 300ms	remaining: 845ms
262:	learn: 0.1845675	total: 300ms	remaining: 842ms
263:	learn: 0.1841927	total: 301ms	remaining: 839ms
264:	learn: 0.1840443	total: 302ms	remaining: 837ms
265:	learn: 0.1832341	total: 302ms	remaining: 834ms
266:	learn: 0.1830562	total: 303ms	remaining: 832ms
267:	learn: 0.1829333	total: 303ms	remaining: 829ms
268:	learn: 0.1821424	total: 304ms	remaining: 827ms
269:	learn: 0.1819225	total: 305ms	remaining: 824ms
270:	learn: 0.1813575	total: 306ms	remaining: 822ms
271:	learn: 0.1812277	total: 306ms	remaining: 820ms
272:	learn: 0.1807493	total: 307ms	remaining: 817ms
273:	learn: 0.1802568	total: 308ms	remaining: 815ms
274:	learn: 0.1801399	total: 308ms	remaining: 812ms
275:	learn: 0.1798596	total: 309ms	remaining: 810ms
276:	learn: 0.1791066	total: 309ms	remaining: 808ms
277:	learn: 0.1790077	total: 310ms	remaining: 805ms
278:	learn: 0.1785280	total: 311ms	remaining: 803ms
279:	learn: 0.1781065	total: 311ms	remaining: 800ms
280:	learn: 0.1778636	total: 312ms	remaining: 798ms
281:	learn: 0.1776580	total: 312ms	remaining: 795ms
282:	learn: 0.1774775	total: 313ms	remaining: 793ms
283:	learn: 0.1773876	total: 314ms	remaining: 791ms
284:	learn: 0.1770624	total: 314ms	remaining: 789ms
285:	learn: 0.1769417	total: 315ms	remaining: 787ms
286:	learn: 0.1764055	total: 316ms	remaining: 784ms
287:	learn: 0.1762011	total: 316ms	remaining: 782ms
288:	learn: 0.1758096	total: 317ms	remaining: 780ms
289:	learn: 0.1755792	total: 318ms	remaining: 777ms
290:	learn: 0.1750477	total: 318ms	remaining: 775ms
291:	learn: 0.1747552	total: 319ms	remaining: 773ms
292:	learn: 0.1744069	total: 320ms	remaining: 771ms
293:	learn: 0.1743103	total: 320ms	remaining: 769ms
294:	learn: 0.1742375	total: 321ms	remaining: 768ms
295:	learn: 0.1736090	total: 322ms	remaining: 766ms
296:	learn: 0.1733544	total: 323ms	remaining: 764ms
297:	learn: 0.1731381	total: 324ms	remaining: 762ms
298:	learn: 0.1728818	total: 324ms	remaining: 761ms
299:	learn: 0.1725631	total: 325ms	remaining: 759ms
300:	learn: 0.1722119	total: 326ms	remaining: 757ms
301:	learn: 0.1721104	total: 326ms	remaining: 754ms
302:	learn: 0.1718888	total: 327ms	remaining: 752ms
303:	learn: 0.1714430	total: 328ms	remaining: 750ms
304:	learn: 0.1712077	total: 328ms	remaining: 748ms
305:	learn: 0.1710824	total: 329ms	remaining: 746ms
306:	learn: 0.1705191	total: 329ms	remaining: 744ms
307:	learn: 0.1704469	total: 330ms	remaining: 741ms
308:	learn: 0.1699205	total: 331ms	remaining: 739ms
309:	learn: 0.1696232	total: 331ms	remaining: 737ms
310:	learn: 0.1693134	total: 332ms	remaining: 735ms
311:	learn: 0.1692391	total: 332ms	remaining: 733ms
312:	learn: 0.1689886	total: 333ms	remaining: 730ms
313:	learn: 0.1687511	total: 333ms	remaining: 728ms
314:	learn: 0.1685106	total: 334ms	remaining: 726ms
315:	learn: 0.1683087	total: 335ms	remaining: 725ms
316:	learn: 0.1680381	total: 336ms	remaining: 723ms
317:	learn: 0.1678605	total: 336ms	remaining: 721ms
318:	learn: 0.1672638	total: 337ms	remaining: 719ms
319:	learn: 0.1671873	total: 337ms	remaining: 716ms
320:	learn: 0.1671008	total: 338ms	remaining: 714ms
321:	learn: 0.1668677	total: 338ms	remaining: 712ms
322:	learn: 0.1667839	total: 339ms	remaining: 710ms
323:	learn: 0.1663254	total: 339ms	remaining: 708ms
324:	learn: 0.1661171	total: 340ms	remaining: 706ms
325:	learn: 0.1655531	total: 340ms	remaining: 704ms
326:	learn: 0.1653348	total: 341ms	remaining: 702ms
327:	learn: 0.1652551	total: 341ms	remaining: 700ms
328:	learn: 0.1651905	total: 342ms	remaining: 698ms
329:	learn: 0.1649711	total: 343ms	remaining: 695ms
330:	learn: 0.1647604	total: 343ms	remaining: 693ms
331:	learn: 0.1641517	total: 344ms	remaining: 691ms
332:	learn: 0.1640680	total: 344ms	remaining: 689ms
333:	learn: 0.1638890	total: 345ms	remaining: 687ms
334:	learn: 0.1637036	total: 345ms	remaining: 685ms
335:	learn: 0.1635065	total: 346ms	remaining: 683ms
336:	learn: 0.1632788	total: 346ms	remaining: 681ms
337:	learn: 0.1631868	total: 347ms	remaining: 679ms
338:	learn: 0.1630640	total: 347ms	remaining: 677ms
339:	learn: 0.1627887	total: 348ms	remaining: 675ms
340:	learn: 0.1627077	total: 349ms	remaining: 675ms
341:	learn: 0.1625438	total: 350ms	remaining: 674ms
342:	learn: 0.1623898	total: 351ms	remaining: 672ms
343:	learn: 0.1621412	total: 351ms	remaining: 670ms
344:	learn: 0.1619469	total: 352ms	remaining: 668ms
345:	learn: 0.1617390	total: 353ms	remaining: 666ms
346:	learn: 0.1615355	total: 353ms	remaining: 664ms
347:	learn: 0.1613430	total: 354ms	remaining: 663ms
348:	learn: 0.1612743	total: 354ms	remaining: 661ms
349:	learn: 0.1612195	total: 355ms	remaining: 659ms
350:	learn: 0.1607788	total: 355ms	remaining: 657ms
351:	learn: 0.1605581	total: 356ms	remaining: 655ms
352:	learn: 0.1601458	total: 356ms	remaining: 653ms
353:	learn: 0.1600267	total: 357ms	remaining: 651ms
354:	learn: 0.1599590	total: 357ms	remaining: 649ms
355:	learn: 0.1598404	total: 358ms	remaining: 647ms
356:	learn: 0.1597849	total: 358ms	remaining: 645ms
357:	learn: 0.1593392	total: 359ms	remaining: 644ms
358:	learn: 0.1591027	total: 359ms	remaining: 642ms
359:	learn: 0.1589126	total: 360ms	remaining: 640ms
360:	learn: 0.1588416	total: 360ms	remaining: 638ms
361:	learn: 0.1583886	total: 361ms	remaining: 636ms
362:	learn: 0.1581238	total: 362ms	remaining: 634ms
363:	learn: 0.1580741	total: 362ms	remaining: 633ms
364:	learn: 0.1578931	total: 362ms	remaining: 631ms
365:	learn: 0.1576791	total: 363ms	remaining: 629ms
366:	learn: 0.1576382	total: 364ms	remaining: 627ms
367:	learn: 0.1573497	total: 364ms	remaining: 626ms
368:	learn: 0.1569657	total: 365ms	remaining: 624ms
369:	learn: 0.1567426	total: 366ms	remaining: 623ms
370:	learn: 0.1562863	total: 366ms	remaining: 621ms
371:	learn: 0.1558069	total: 367ms	remaining: 619ms
372:	learn: 0.1553211	total: 367ms	remaining: 618ms
373:	learn: 0.1551317	total: 368ms	remaining: 616ms
374:	learn: 0.1549726	total: 368ms	remaining: 614ms
375:	learn: 0.1545611	total: 369ms	remaining: 612ms
376:	learn: 0.1543205	total: 369ms	remaining: 611ms
377:	learn: 0.1539921	total: 370ms	remaining: 609ms
378:	learn: 0.1538182	total: 371ms	remaining: 607ms
379:	learn: 0.1536034	total: 371ms	remaining: 605ms

In [22]:
XGB_reg_all, LGBM_reg_all, model_CB_all = train_best_reg_models(df_all, relevant_columns_all)

Error metrics for XGBoost regression model :
The median absolute error is: 0.03
The mean absolute error is: 0.14
The root mean squared error is: 0.24
Error metrics for LightGBM regression model :
The median absolute error is: 0.10
The mean absolute error is: 0.15
The root mean squared error is: 0.21
Learning rate set to 0.031087
0:	learn: 0.3583654	total: 978us	remaining: 977ms
1:	learn: 0.3523087	total: 1.78ms	remaining: 890ms
2:	learn: 0.3461321	total: 2.48ms	remaining: 826ms
3:	learn: 0.3408202	total: 3.2ms	remaining: 797ms
4:	learn: 0.3353947	total: 3.8ms	remaining: 756ms
5:	learn: 0.3293397	total: 4.48ms	remaining: 743ms
6:	learn: 0.3240805	total: 5.23ms	remaining: 742ms
7:	learn: 0.3178228	total: 5.97ms	remaining: 740ms
8:	learn: 0.3129384	total: 6.72ms	remaining: 740ms
9:	learn: 0.3081758	total: 7.58ms	remaining: 750ms
10:	learn: 0.3038116	total: 8.43ms	remaining: 758ms
11:	learn: 0.2988721	total: 9.13ms	remaining: 752ms
12:	learn: 0.2940285	total: 9.82ms	remaining: 746ms
13:	learn: 0.2896696	total: 10.5ms	remaining: 741ms
14:	learn: 0.2850199	total: 11.2ms	remaining: 736ms
15:	learn: 0.2808999	total: 11.8ms	remaining: 729ms
16:	learn: 0.2768976	total: 12.5ms	remaining: 723ms
17:	learn: 0.2730486	total: 13.4ms	remaining: 729ms
18:	learn: 0.2690354	total: 14ms	remaining: 725ms
19:	learn: 0.2649525	total: 14.7ms	remaining: 721ms
20:	learn: 0.2616441	total: 15.5ms	remaining: 723ms
21:	learn: 0.2578133	total: 16.5ms	remaining: 732ms
22:	learn: 0.2547828	total: 17.3ms	remaining: 736ms
23:	learn: 0.2513171	total: 18.1ms	remaining: 735ms
24:	learn: 0.2474122	total: 18.8ms	remaining: 734ms
25:	learn: 0.2440137	total: 19.5ms	remaining: 729ms
26:	learn: 0.2411740	total: 20.1ms	remaining: 724ms
27:	learn: 0.2383670	total: 20.8ms	remaining: 721ms
28:	learn: 0.2357983	total: 21.5ms	remaining: 719ms
29:	learn: 0.2329905	total: 22.1ms	remaining: 715ms
30:	learn: 0.2299975	total: 22.8ms	remaining: 711ms
31:	learn: 0.2278544	total: 23.5ms	remaining: 712ms
32:	learn: 0.2251542	total: 24.2ms	remaining: 709ms
33:	learn: 0.2226044	total: 25ms	remaining: 710ms
34:	learn: 0.2201709	total: 25.7ms	remaining: 710ms
35:	learn: 0.2179502	total: 26.4ms	remaining: 707ms
36:	learn: 0.2158290	total: 27.1ms	remaining: 706ms
37:	learn: 0.2137643	total: 27.9ms	remaining: 705ms
38:	learn: 0.2114902	total: 28.6ms	remaining: 705ms
39:	learn: 0.2098647	total: 29.4ms	remaining: 705ms
40:	learn: 0.2082315	total: 30.1ms	remaining: 703ms
41:	learn: 0.2064565	total: 30.7ms	remaining: 701ms
42:	learn: 0.2045257	total: 31.4ms	remaining: 699ms
43:	learn: 0.2025973	total: 32.1ms	remaining: 698ms
44:	learn: 0.2009121	total: 32.8ms	remaining: 696ms
45:	learn: 0.1989795	total: 33.5ms	remaining: 694ms
46:	learn: 0.1971909	total: 34.3ms	remaining: 694ms
47:	learn: 0.1956455	total: 35ms	remaining: 695ms
48:	learn: 0.1940619	total: 35.8ms	remaining: 695ms
49:	learn: 0.1928503	total: 36.5ms	remaining: 694ms
50:	learn: 0.1913639	total: 37.2ms	remaining: 692ms
51:	learn: 0.1899508	total: 37.8ms	remaining: 690ms
52:	learn: 0.1884424	total: 38.5ms	remaining: 688ms
53:	learn: 0.1868435	total: 39.2ms	remaining: 686ms
54:	learn: 0.1855040	total: 39.4ms	remaining: 678ms
55:	learn: 0.1842347	total: 40.1ms	remaining: 677ms
56:	learn: 0.1828517	total: 40.8ms	remaining: 675ms
57:	learn: 0.1813588	total: 41.5ms	remaining: 674ms
58:	learn: 0.1798940	total: 42.2ms	remaining: 673ms
59:	learn: 0.1790468	total: 43ms	remaining: 674ms
60:	learn: 0.1781286	total: 43.8ms	remaining: 674ms
61:	learn: 0.1769463	total: 44.6ms	remaining: 675ms
62:	learn: 0.1756527	total: 45.4ms	remaining: 675ms
63:	learn: 0.1743614	total: 46.2ms	remaining: 675ms
64:	learn: 0.1731591	total: 46.9ms	remaining: 675ms
65:	learn: 0.1719440	total: 47.6ms	remaining: 674ms
66:	learn: 0.1710288	total: 48.3ms	remaining: 673ms
67:	learn: 0.1701615	total: 49ms	remaining: 671ms
68:	learn: 0.1686838	total: 49.7ms	remaining: 670ms
69:	learn: 0.1676854	total: 50.4ms	remaining: 669ms
70:	learn: 0.1666406	total: 51.1ms	remaining: 668ms
71:	learn: 0.1659174	total: 51.8ms	remaining: 668ms
72:	learn: 0.1650753	total: 52.6ms	remaining: 668ms
73:	learn: 0.1642946	total: 53.4ms	remaining: 668ms
74:	learn: 0.1634627	total: 54.2ms	remaining: 669ms
75:	learn: 0.1626424	total: 55ms	remaining: 668ms
76:	learn: 0.1619600	total: 55.5ms	remaining: 665ms
77:	learn: 0.1612864	total: 56.1ms	remaining: 663ms
78:	learn: 0.1606000	total: 56.9ms	remaining: 663ms
79:	learn: 0.1598122	total: 57.7ms	remaining: 664ms
80:	learn: 0.1591868	total: 58.5ms	remaining: 664ms
81:	learn: 0.1585606	total: 59.3ms	remaining: 664ms
82:	learn: 0.1576761	total: 60.1ms	remaining: 664ms
83:	learn: 0.1571327	total: 60.9ms	remaining: 664ms
84:	learn: 0.1565459	total: 61.6ms	remaining: 663ms
85:	learn: 0.1559214	total: 62.3ms	remaining: 662ms
86:	learn: 0.1550888	total: 63ms	remaining: 662ms
87:	learn: 0.1544044	total: 63.7ms	remaining: 660ms
88:	learn: 0.1537402	total: 64.4ms	remaining: 659ms
89:	learn: 0.1530889	total: 65ms	remaining: 657ms
90:	learn: 0.1526718	total: 65.7ms	remaining: 657ms
91:	learn: 0.1522144	total: 66.4ms	remaining: 656ms
92:	learn: 0.1515203	total: 67.1ms	remaining: 654ms
93:	learn: 0.1505325	total: 67.8ms	remaining: 653ms
94:	learn: 0.1498342	total: 68.5ms	remaining: 652ms
95:	learn: 0.1492866	total: 69.2ms	remaining: 651ms
96:	learn: 0.1486741	total: 69.9ms	remaining: 650ms
97:	learn: 0.1481194	total: 70.6ms	remaining: 650ms
98:	learn: 0.1476245	total: 71.4ms	remaining: 649ms
99:	learn: 0.1471005	total: 72.1ms	remaining: 649ms
100:	learn: 0.1465211	total: 73ms	remaining: 650ms
101:	learn: 0.1460261	total: 73.8ms	remaining: 650ms
102:	learn: 0.1455375	total: 74.6ms	remaining: 650ms
103:	learn: 0.1449893	total: 75.1ms	remaining: 647ms
104:	learn: 0.1443114	total: 75.8ms	remaining: 646ms
105:	learn: 0.1438505	total: 76.5ms	remaining: 645ms
106:	learn: 0.1430861	total: 77.1ms	remaining: 644ms
107:	learn: 0.1427455	total: 77.4ms	remaining: 639ms
108:	learn: 0.1420799	total: 78ms	remaining: 638ms
109:	learn: 0.1415090	total: 78.6ms	remaining: 636ms
110:	learn: 0.1411496	total: 79.3ms	remaining: 635ms
111:	learn: 0.1406289	total: 80ms	remaining: 634ms
112:	learn: 0.1403238	total: 80.6ms	remaining: 633ms
113:	learn: 0.1397100	total: 81.2ms	remaining: 631ms
114:	learn: 0.1392928	total: 81.8ms	remaining: 630ms
115:	learn: 0.1387128	total: 82.4ms	remaining: 628ms
116:	learn: 0.1382295	total: 83ms	remaining: 626ms
117:	learn: 0.1377247	total: 83.5ms	remaining: 624ms
118:	learn: 0.1370085	total: 84.1ms	remaining: 623ms
119:	learn: 0.1365399	total: 84.7ms	remaining: 621ms
120:	learn: 0.1357850	total: 85.3ms	remaining: 620ms
121:	learn: 0.1352810	total: 85.9ms	remaining: 618ms
122:	learn: 0.1348374	total: 86.5ms	remaining: 617ms
123:	learn: 0.1345058	total: 87.2ms	remaining: 616ms
124:	learn: 0.1340968	total: 88.1ms	remaining: 617ms
125:	learn: 0.1336143	total: 89ms	remaining: 617ms
126:	learn: 0.1331860	total: 89.7ms	remaining: 617ms
127:	learn: 0.1326838	total: 90.5ms	remaining: 616ms
128:	learn: 0.1323169	total: 91ms	remaining: 615ms
129:	learn: 0.1320522	total: 91.7ms	remaining: 614ms
130:	learn: 0.1314892	total: 92.4ms	remaining: 613ms
131:	learn: 0.1309553	total: 93.1ms	remaining: 612ms
132:	learn: 0.1305321	total: 93.6ms	remaining: 610ms
133:	learn: 0.1299927	total: 94.2ms	remaining: 609ms
134:	learn: 0.1295609	total: 94.9ms	remaining: 608ms
135:	learn: 0.1292009	total: 95.6ms	remaining: 607ms
136:	learn: 0.1287211	total: 96.1ms	remaining: 605ms
137:	learn: 0.1284595	total: 96.9ms	remaining: 605ms
138:	learn: 0.1280239	total: 97.6ms	remaining: 605ms
139:	learn: 0.1277075	total: 98.2ms	remaining: 603ms
140:	learn: 0.1273044	total: 98.8ms	remaining: 602ms
141:	learn: 0.1268084	total: 99.4ms	remaining: 600ms
142:	learn: 0.1265146	total: 100ms	remaining: 599ms
143:	learn: 0.1259430	total: 101ms	remaining: 599ms
144:	learn: 0.1255621	total: 101ms	remaining: 597ms
145:	learn: 0.1250039	total: 102ms	remaining: 597ms
146:	learn: 0.1246599	total: 103ms	remaining: 596ms
147:	learn: 0.1243446	total: 103ms	remaining: 595ms
148:	learn: 0.1239327	total: 104ms	remaining: 594ms
149:	learn: 0.1234844	total: 105ms	remaining: 593ms
150:	learn: 0.1231056	total: 105ms	remaining: 592ms
151:	learn: 0.1226837	total: 106ms	remaining: 591ms
152:	learn: 0.1222882	total: 107ms	remaining: 591ms
153:	learn: 0.1219493	total: 107ms	remaining: 590ms
154:	learn: 0.1216491	total: 108ms	remaining: 589ms
155:	learn: 0.1212149	total: 109ms	remaining: 587ms
156:	learn: 0.1208021	total: 109ms	remaining: 586ms
157:	learn: 0.1205741	total: 110ms	remaining: 585ms
158:	learn: 0.1201747	total: 110ms	remaining: 584ms
159:	learn: 0.1196550	total: 111ms	remaining: 582ms
160:	learn: 0.1193495	total: 112ms	remaining: 581ms
161:	learn: 0.1188767	total: 112ms	remaining: 580ms
162:	learn: 0.1183501	total: 113ms	remaining: 580ms
163:	learn: 0.1179192	total: 114ms	remaining: 579ms
164:	learn: 0.1175131	total: 114ms	remaining: 578ms
165:	learn: 0.1170450	total: 115ms	remaining: 577ms
166:	learn: 0.1165772	total: 116ms	remaining: 576ms
167:	learn: 0.1163321	total: 116ms	remaining: 575ms
168:	learn: 0.1160790	total: 117ms	remaining: 574ms
169:	learn: 0.1158193	total: 117ms	remaining: 573ms
170:	learn: 0.1154461	total: 118ms	remaining: 573ms
171:	learn: 0.1149387	total: 119ms	remaining: 573ms
172:	learn: 0.1146849	total: 120ms	remaining: 573ms
173:	learn: 0.1141512	total: 120ms	remaining: 572ms
174:	learn: 0.1134712	total: 121ms	remaining: 571ms
175:	learn: 0.1131077	total: 122ms	remaining: 570ms
176:	learn: 0.1128372	total: 122ms	remaining: 569ms
177:	learn: 0.1125513	total: 123ms	remaining: 568ms
178:	learn: 0.1122276	total: 124ms	remaining: 567ms
179:	learn: 0.1119637	total: 124ms	remaining: 567ms
180:	learn: 0.1115884	total: 125ms	remaining: 566ms
181:	learn: 0.1113349	total: 126ms	remaining: 564ms
182:	learn: 0.1110035	total: 126ms	remaining: 563ms
183:	learn: 0.1106425	total: 127ms	remaining: 562ms
184:	learn: 0.1102528	total: 127ms	remaining: 561ms
185:	learn: 0.1098931	total: 128ms	remaining: 560ms
186:	learn: 0.1097182	total: 129ms	remaining: 559ms
187:	learn: 0.1093558	total: 129ms	remaining: 558ms
188:	learn: 0.1089612	total: 130ms	remaining: 557ms
189:	learn: 0.1086073	total: 130ms	remaining: 556ms
190:	learn: 0.1083272	total: 131ms	remaining: 555ms
191:	learn: 0.1079353	total: 132ms	remaining: 554ms
192:	learn: 0.1075221	total: 132ms	remaining: 553ms
193:	learn: 0.1070618	total: 133ms	remaining: 554ms
194:	learn: 0.1066091	total: 134ms	remaining: 555ms
195:	learn: 0.1060176	total: 135ms	remaining: 555ms
196:	learn: 0.1055858	total: 136ms	remaining: 554ms
197:	learn: 0.1053071	total: 137ms	remaining: 553ms
198:	learn: 0.1049458	total: 137ms	remaining: 552ms
199:	learn: 0.1045932	total: 138ms	remaining: 552ms
200:	learn: 0.1042226	total: 139ms	remaining: 551ms
201:	learn: 0.1037660	total: 139ms	remaining: 551ms
202:	learn: 0.1032771	total: 140ms	remaining: 550ms
203:	learn: 0.1029798	total: 141ms	remaining: 550ms
204:	learn: 0.1028150	total: 142ms	remaining: 549ms
205:	learn: 0.1023774	total: 142ms	remaining: 548ms
206:	learn: 0.1018942	total: 144ms	remaining: 553ms
207:	learn: 0.1015228	total: 145ms	remaining: 552ms
208:	learn: 0.1012440	total: 146ms	remaining: 551ms
209:	learn: 0.1009473	total: 146ms	remaining: 551ms
210:	learn: 0.1005234	total: 147ms	remaining: 551ms
211:	learn: 0.1002366	total: 148ms	remaining: 551ms
212:	learn: 0.0999864	total: 149ms	remaining: 550ms
213:	learn: 0.0995793	total: 150ms	remaining: 550ms
214:	learn: 0.0992726	total: 150ms	remaining: 549ms
215:	learn: 0.0988789	total: 151ms	remaining: 548ms
216:	learn: 0.0984504	total: 152ms	remaining: 547ms
217:	learn: 0.0982822	total: 152ms	remaining: 546ms
218:	learn: 0.0980981	total: 153ms	remaining: 546ms
219:	learn: 0.0977232	total: 154ms	remaining: 545ms
220:	learn: 0.0974394	total: 154ms	remaining: 544ms
221:	learn: 0.0972247	total: 155ms	remaining: 542ms
222:	learn: 0.0967566	total: 155ms	remaining: 541ms
223:	learn: 0.0963322	total: 156ms	remaining: 541ms
224:	learn: 0.0959113	total: 157ms	remaining: 540ms
225:	learn: 0.0954910	total: 157ms	remaining: 539ms
226:	learn: 0.0951952	total: 158ms	remaining: 538ms
227:	learn: 0.0947664	total: 158ms	remaining: 536ms
228:	learn: 0.0944303	total: 159ms	remaining: 535ms
229:	learn: 0.0940462	total: 160ms	remaining: 535ms
230:	learn: 0.0937847	total: 160ms	remaining: 534ms
231:	learn: 0.0934712	total: 161ms	remaining: 533ms
232:	learn: 0.0932962	total: 162ms	remaining: 532ms
233:	learn: 0.0929651	total: 163ms	remaining: 532ms
234:	learn: 0.0927076	total: 164ms	remaining: 533ms
235:	learn: 0.0925825	total: 164ms	remaining: 532ms
236:	learn: 0.0922202	total: 165ms	remaining: 532ms
237:	learn: 0.0918765	total: 166ms	remaining: 531ms
238:	learn: 0.0915643	total: 166ms	remaining: 530ms
239:	learn: 0.0912368	total: 167ms	remaining: 529ms
240:	learn: 0.0910439	total: 168ms	remaining: 528ms
241:	learn: 0.0907132	total: 168ms	remaining: 527ms
242:	learn: 0.0904929	total: 169ms	remaining: 527ms
243:	learn: 0.0900811	total: 170ms	remaining: 526ms
244:	learn: 0.0897149	total: 170ms	remaining: 525ms
245:	learn: 0.0894816	total: 171ms	remaining: 523ms
246:	learn: 0.0892068	total: 171ms	remaining: 523ms
247:	learn: 0.0889469	total: 172ms	remaining: 521ms
248:	learn: 0.0888249	total: 172ms	remaining: 520ms
249:	learn: 0.0885854	total: 173ms	remaining: 519ms
250:	learn: 0.0883330	total: 174ms	remaining: 518ms
251:	learn: 0.0881444	total: 174ms	remaining: 517ms
252:	learn: 0.0878955	total: 175ms	remaining: 516ms
253:	learn: 0.0875818	total: 175ms	remaining: 515ms
254:	learn: 0.0872585	total: 176ms	remaining: 514ms
255:	learn: 0.0872195	total: 177ms	remaining: 513ms
256:	learn: 0.0868259	total: 177ms	remaining: 513ms
257:	learn: 0.0865035	total: 178ms	remaining: 512ms
258:	learn: 0.0862517	total: 179ms	remaining: 512ms
259:	learn: 0.0859021	total: 180ms	remaining: 511ms
260:	learn: 0.0856436	total: 180ms	remaining: 510ms
261:	learn: 0.0853047	total: 181ms	remaining: 510ms
262:	learn: 0.0851220	total: 182ms	remaining: 509ms
263:	learn: 0.0847945	total: 182ms	remaining: 508ms
264:	learn: 0.0844458	total: 183ms	remaining: 507ms
265:	learn: 0.0842234	total: 183ms	remaining: 506ms
266:	learn: 0.0840953	total: 184ms	remaining: 505ms
267:	learn: 0.0837805	total: 184ms	remaining: 504ms
268:	learn: 0.0835783	total: 185ms	remaining: 503ms
269:	learn: 0.0832742	total: 186ms	remaining: 502ms
270:	learn: 0.0829659	total: 186ms	remaining: 501ms
271:	learn: 0.0825588	total: 187ms	remaining: 501ms
272:	learn: 0.0822469	total: 188ms	remaining: 500ms
273:	learn: 0.0819516	total: 188ms	remaining: 499ms
274:	learn: 0.0816116	total: 189ms	remaining: 498ms
275:	learn: 0.0813987	total: 189ms	remaining: 497ms
276:	learn: 0.0809582	total: 190ms	remaining: 496ms
277:	learn: 0.0806601	total: 191ms	remaining: 495ms
278:	learn: 0.0805433	total: 191ms	remaining: 494ms
279:	learn: 0.0803565	total: 192ms	remaining: 494ms
280:	learn: 0.0800666	total: 193ms	remaining: 493ms
281:	learn: 0.0798668	total: 193ms	remaining: 493ms
282:	learn: 0.0796321	total: 194ms	remaining: 492ms
283:	learn: 0.0793611	total: 195ms	remaining: 492ms
284:	learn: 0.0790701	total: 196ms	remaining: 491ms
285:	learn: 0.0788288	total: 197ms	remaining: 491ms
286:	learn: 0.0786567	total: 197ms	remaining: 490ms
287:	learn: 0.0784359	total: 198ms	remaining: 489ms
288:	learn: 0.0782912	total: 198ms	remaining: 488ms
289:	learn: 0.0777821	total: 199ms	remaining: 487ms
290:	learn: 0.0775327	total: 200ms	remaining: 487ms
291:	learn: 0.0770368	total: 200ms	remaining: 486ms
292:	learn: 0.0768179	total: 201ms	remaining: 485ms
293:	learn: 0.0766535	total: 202ms	remaining: 484ms
294:	learn: 0.0764444	total: 202ms	remaining: 483ms
295:	learn: 0.0761421	total: 203ms	remaining: 482ms
296:	learn: 0.0759909	total: 203ms	remaining: 481ms
297:	learn: 0.0757567	total: 204ms	remaining: 481ms
298:	learn: 0.0754112	total: 205ms	remaining: 480ms
299:	learn: 0.0751819	total: 205ms	remaining: 479ms
300:	learn: 0.0749682	total: 206ms	remaining: 479ms
301:	learn: 0.0747102	total: 207ms	remaining: 478ms
302:	learn: 0.0743510	total: 208ms	remaining: 477ms
303:	learn: 0.0741901	total: 208ms	remaining: 477ms
304:	learn: 0.0739867	total: 209ms	remaining: 476ms
305:	learn: 0.0737968	total: 210ms	remaining: 475ms
306:	learn: 0.0735904	total: 210ms	remaining: 474ms
307:	learn: 0.0733557	total: 211ms	remaining: 474ms
308:	learn: 0.0730153	total: 211ms	remaining: 473ms
309:	learn: 0.0727600	total: 212ms	remaining: 472ms
310:	learn: 0.0726080	total: 213ms	remaining: 471ms
311:	learn: 0.0724173	total: 213ms	remaining: 470ms
312:	learn: 0.0721470	total: 214ms	remaining: 470ms
313:	learn: 0.0721221	total: 215ms	remaining: 469ms
314:	learn: 0.0720776	total: 215ms	remaining: 468ms
315:	learn: 0.0718455	total: 216ms	remaining: 468ms
316:	learn: 0.0714735	total: 217ms	remaining: 467ms
317:	learn: 0.0713304	total: 217ms	remaining: 466ms
318:	learn: 0.0711645	total: 218ms	remaining: 465ms
319:	learn: 0.0710077	total: 219ms	remaining: 465ms
320:	learn: 0.0708622	total: 219ms	remaining: 464ms
321:	learn: 0.0705584	total: 220ms	remaining: 463ms
322:	learn: 0.0704400	total: 220ms	remaining: 462ms
323:	learn: 0.0702811	total: 221ms	remaining: 461ms
324:	learn: 0.0700658	total: 222ms	remaining: 460ms
325:	learn: 0.0699249	total: 222ms	remaining: 460ms
326:	learn: 0.0696658	total: 223ms	remaining: 459ms
327:	learn: 0.0694978	total: 224ms	remaining: 459ms
328:	learn: 0.0693179	total: 225ms	remaining: 458ms
329:	learn: 0.0692887	total: 225ms	remaining: 457ms
330:	learn: 0.0691571	total: 226ms	remaining: 456ms
331:	learn: 0.0690323	total: 226ms	remaining: 456ms
332:	learn: 0.0687923	total: 227ms	remaining: 455ms
333:	learn: 0.0684765	total: 228ms	remaining: 454ms
334:	learn: 0.0684544	total: 228ms	remaining: 453ms
335:	learn: 0.0683120	total: 229ms	remaining: 452ms
336:	learn: 0.0680751	total: 229ms	remaining: 451ms
337:	learn: 0.0678502	total: 230ms	remaining: 451ms
338:	learn: 0.0676448	total: 231ms	remaining: 450ms
339:	learn: 0.0674167	total: 231ms	remaining: 449ms
340:	learn: 0.0672560	total: 232ms	remaining: 449ms
341:	learn: 0.0670457	total: 233ms	remaining: 448ms
342:	learn: 0.0668714	total: 233ms	remaining: 447ms
343:	learn: 0.0666720	total: 234ms	remaining: 446ms
344:	learn: 0.0664469	total: 235ms	remaining: 445ms
345:	learn: 0.0662687	total: 235ms	remaining: 445ms
346:	learn: 0.0662463	total: 236ms	remaining: 444ms
347:	learn: 0.0660205	total: 236ms	remaining: 443ms
348:	learn: 0.0657679	total: 237ms	remaining: 442ms
349:	learn: 0.0655491	total: 238ms	remaining: 442ms
350:	learn: 0.0653739	total: 239ms	remaining: 441ms
351:	learn: 0.0652217	total: 239ms	remaining: 440ms
352:	learn: 0.0651434	total: 240ms	remaining: 440ms
353:	learn: 0.0649719	total: 240ms	remaining: 439ms
354:	learn: 0.0646880	total: 241ms	remaining: 438ms
355:	learn: 0.0644787	total: 242ms	remaining: 437ms
356:	learn: 0.0644572	total: 242ms	remaining: 437ms
357:	learn: 0.0642497	total: 243ms	remaining: 436ms
358:	learn: 0.0640308	total: 244ms	remaining: 435ms
359:	learn: 0.0638871	total: 244ms	remaining: 434ms
360:	learn: 0.0638669	total: 245ms	remaining: 433ms
361:	learn: 0.0637171	total: 246ms	remaining: 433ms
362:	learn: 0.0635505	total: 246ms	remaining: 432ms
363:	learn: 0.0635284	total: 247ms	remaining: 431ms
364:	learn: 0.0633268	total: 247ms	remaining: 430ms
365:	learn: 0.0631821	total: 248ms	remaining: 429ms
366:	learn: 0.0630657	total: 248ms	remaining: 429ms
367:	learn: 0.0628143	total: 249ms	remaining: 428ms
368:	learn: 0.0627043	total: 250ms	remaining: 427ms
369:	learn: 0.0623980	total: 250ms	remaining: 426ms
370:	learn: 0.0622950	total: 251ms	remaining: 426ms
371:	learn: 0.0621414	total: 252ms	remaining: 425ms
372:	learn: 0.0619731	total: 252ms	remaining: 424ms
373:	learn: 0.0618881	total: 253ms	remaining: 424ms
374:	learn: 0.0616796	total: 254ms	remaining: 423ms
375:	learn: 0.0614627	total: 254ms	remaining: 422ms
376:	learn: 0.0613880	total: 255ms	remaining: 421ms
377:	learn: 0.0612377	total: 256ms	remaining: 421ms

In [23]:
XGB_reg_all_plus_plus, LGBM_reg_all_plus_plus, model_CB_all_plus_plus = train_best_reg_models(df_all_plus_plus, relevant_columns_all_plus_plus)

Error metrics for XGBoost regression model :
The median absolute error is: 0.10
The mean absolute error is: 0.16
The root mean squared error is: 0.23
Error metrics for LightGBM regression model :
The median absolute error is: 0.15
The mean absolute error is: 0.18
The root mean squared error is: 0.23
Learning rate set to 0.029768
0:	learn: 0.3267196	total: 1.23ms	remaining: 1.23s
1:	learn: 0.3231734	total: 2.49ms	remaining: 1.24s
2:	learn: 0.3194253	total: 3.86ms	remaining: 1.28s
3:	learn: 0.3147255	total: 5.23ms	remaining: 1.3s
4:	learn: 0.3114141	total: 6.43ms	remaining: 1.28s
5:	learn: 0.3081026	total: 7.7ms	remaining: 1.27s
6:	learn: 0.3046576	total: 8.85ms	remaining: 1.25s
7:	learn: 0.3004898	total: 10.1ms	remaining: 1.25s
8:	learn: 0.2968471	total: 11.2ms	remaining: 1.24s
9:	learn: 0.2931533	total: 12.4ms	remaining: 1.23s
10:	learn: 0.2894780	total: 13.5ms	remaining: 1.21s
11:	learn: 0.2864107	total: 14.6ms	remaining: 1.2s
12:	learn: 0.2837885	total: 15.5ms	remaining: 1.17s
13:	learn: 0.2810190	total: 16.5ms	remaining: 1.16s
14:	learn: 0.2782301	total: 17.6ms	remaining: 1.16s
15:	learn: 0.2760040	total: 19ms	remaining: 1.17s
16:	learn: 0.2732826	total: 20.4ms	remaining: 1.18s
17:	learn: 0.2704036	total: 21.7ms	remaining: 1.18s
18:	learn: 0.2678040	total: 23.2ms	remaining: 1.2s
19:	learn: 0.2648998	total: 24.4ms	remaining: 1.2s
20:	learn: 0.2625111	total: 25.6ms	remaining: 1.19s
21:	learn: 0.2598259	total: 26.8ms	remaining: 1.19s
22:	learn: 0.2571383	total: 27.9ms	remaining: 1.18s
23:	learn: 0.2545918	total: 29ms	remaining: 1.18s
24:	learn: 0.2522815	total: 30.2ms	remaining: 1.18s
25:	learn: 0.2500623	total: 31.4ms	remaining: 1.18s
26:	learn: 0.2479275	total: 32.7ms	remaining: 1.18s
27:	learn: 0.2455051	total: 34ms	remaining: 1.18s
28:	learn: 0.2431117	total: 35.1ms	remaining: 1.17s
29:	learn: 0.2409117	total: 36.2ms	remaining: 1.17s
30:	learn: 0.2390055	total: 37.3ms	remaining: 1.17s
31:	learn: 0.2367027	total: 38.5ms	remaining: 1.16s
32:	learn: 0.2346749	total: 39.6ms	remaining: 1.16s
33:	learn: 0.2328111	total: 40.8ms	remaining: 1.16s
34:	learn: 0.2310779	total: 42ms	remaining: 1.16s
35:	learn: 0.2293801	total: 43.2ms	remaining: 1.16s
36:	learn: 0.2276340	total: 44.4ms	remaining: 1.15s
37:	learn: 0.2255674	total: 45.5ms	remaining: 1.15s
38:	learn: 0.2237459	total: 46.7ms	remaining: 1.15s
39:	learn: 0.2224225	total: 47.8ms	remaining: 1.15s
40:	learn: 0.2212123	total: 49ms	remaining: 1.15s
41:	learn: 0.2192219	total: 50.3ms	remaining: 1.15s
42:	learn: 0.2177990	total: 51.5ms	remaining: 1.15s
43:	learn: 0.2163249	total: 52.6ms	remaining: 1.14s
44:	learn: 0.2145280	total: 53.8ms	remaining: 1.14s
45:	learn: 0.2130318	total: 54.9ms	remaining: 1.14s
46:	learn: 0.2113959	total: 56ms	remaining: 1.14s
47:	learn: 0.2102700	total: 57.1ms	remaining: 1.13s
48:	learn: 0.2088930	total: 58.7ms	remaining: 1.14s
49:	learn: 0.2076332	total: 60ms	remaining: 1.14s
50:	learn: 0.2063363	total: 61.3ms	remaining: 1.14s
51:	learn: 0.2047686	total: 62.6ms	remaining: 1.14s
52:	learn: 0.2032457	total: 63.9ms	remaining: 1.14s
53:	learn: 0.2014649	total: 64.9ms	remaining: 1.14s
54:	learn: 0.1999442	total: 66.1ms	remaining: 1.13s
55:	learn: 0.1988723	total: 67.3ms	remaining: 1.13s
56:	learn: 0.1978260	total: 68.4ms	remaining: 1.13s
57:	learn: 0.1963912	total: 69.5ms	remaining: 1.13s
58:	learn: 0.1947620	total: 70.7ms	remaining: 1.13s
59:	learn: 0.1936601	total: 71.8ms	remaining: 1.12s
60:	learn: 0.1920302	total: 72.9ms	remaining: 1.12s
61:	learn: 0.1909938	total: 74ms	remaining: 1.12s
62:	learn: 0.1899119	total: 75.1ms	remaining: 1.12s
63:	learn: 0.1887512	total: 76.5ms	remaining: 1.12s
64:	learn: 0.1874457	total: 77.8ms	remaining: 1.12s
65:	learn: 0.1864481	total: 79.3ms	remaining: 1.12s
66:	learn: 0.1852091	total: 80.7ms	remaining: 1.12s
67:	learn: 0.1839102	total: 81.9ms	remaining: 1.12s
68:	learn: 0.1831807	total: 83ms	remaining: 1.12s
69:	learn: 0.1822871	total: 84.1ms	remaining: 1.12s
70:	learn: 0.1810524	total: 85.2ms	remaining: 1.11s
71:	learn: 0.1799056	total: 86.3ms	remaining: 1.11s
72:	learn: 0.1789191	total: 87.3ms	remaining: 1.11s
73:	learn: 0.1777332	total: 88.3ms	remaining: 1.1s
74:	learn: 0.1765705	total: 89.4ms	remaining: 1.1s
75:	learn: 0.1753019	total: 90.3ms	remaining: 1.1s
76:	learn: 0.1739987	total: 91.3ms	remaining: 1.09s
77:	learn: 0.1731777	total: 92.2ms	remaining: 1.09s
78:	learn: 0.1722157	total: 93.4ms	remaining: 1.09s
79:	learn: 0.1713851	total: 94.7ms	remaining: 1.09s
80:	learn: 0.1705593	total: 96ms	remaining: 1.09s
81:	learn: 0.1695522	total: 97.1ms	remaining: 1.09s
82:	learn: 0.1684016	total: 98ms	remaining: 1.08s
83:	learn: 0.1677863	total: 99ms	remaining: 1.08s
84:	learn: 0.1670384	total: 99.8ms	remaining: 1.07s
85:	learn: 0.1657083	total: 101ms	remaining: 1.07s
86:	learn: 0.1648235	total: 102ms	remaining: 1.07s
87:	learn: 0.1640644	total: 103ms	remaining: 1.06s
88:	learn: 0.1629176	total: 104ms	remaining: 1.06s
89:	learn: 0.1620387	total: 105ms	remaining: 1.06s
90:	learn: 0.1613425	total: 106ms	remaining: 1.06s
91:	learn: 0.1602154	total: 107ms	remaining: 1.05s
92:	learn: 0.1595408	total: 108ms	remaining: 1.05s
93:	learn: 0.1586154	total: 109ms	remaining: 1.05s
94:	learn: 0.1582305	total: 110ms	remaining: 1.05s
95:	learn: 0.1575529	total: 111ms	remaining: 1.05s
96:	learn: 0.1566160	total: 112ms	remaining: 1.05s
97:	learn: 0.1556853	total: 114ms	remaining: 1.04s
98:	learn: 0.1552626	total: 114ms	remaining: 1.04s
99:	learn: 0.1548075	total: 115ms	remaining: 1.04s
100:	learn: 0.1539601	total: 116ms	remaining: 1.03s
101:	learn: 0.1532230	total: 117ms	remaining: 1.03s
102:	learn: 0.1527822	total: 118ms	remaining: 1.03s
103:	learn: 0.1519701	total: 119ms	remaining: 1.03s
104:	learn: 0.1513629	total: 120ms	remaining: 1.02s
105:	learn: 0.1505242	total: 121ms	remaining: 1.02s
106:	learn: 0.1500681	total: 122ms	remaining: 1.02s
107:	learn: 0.1495157	total: 123ms	remaining: 1.02s
108:	learn: 0.1489535	total: 124ms	remaining: 1.02s
109:	learn: 0.1483588	total: 126ms	remaining: 1.01s
110:	learn: 0.1479039	total: 127ms	remaining: 1.01s
111:	learn: 0.1473337	total: 128ms	remaining: 1.01s
112:	learn: 0.1462507	total: 129ms	remaining: 1.01s
113:	learn: 0.1452737	total: 130ms	remaining: 1.01s
114:	learn: 0.1448238	total: 131ms	remaining: 1s
115:	learn: 0.1443746	total: 132ms	remaining: 1s
116:	learn: 0.1437452	total: 133ms	remaining: 1s
117:	learn: 0.1433367	total: 134ms	remaining: 1s
118:	learn: 0.1428097	total: 135ms	remaining: 998ms
119:	learn: 0.1423667	total: 136ms	remaining: 995ms
120:	learn: 0.1419376	total: 137ms	remaining: 993ms
121:	learn: 0.1415410	total: 138ms	remaining: 991ms
122:	learn: 0.1410442	total: 139ms	remaining: 988ms
123:	learn: 0.1405294	total: 140ms	remaining: 989ms
124:	learn: 0.1398322	total: 142ms	remaining: 991ms
125:	learn: 0.1393250	total: 143ms	remaining: 991ms
126:	learn: 0.1386375	total: 144ms	remaining: 989ms
127:	learn: 0.1378194	total: 145ms	remaining: 986ms
128:	learn: 0.1371155	total: 146ms	remaining: 984ms
129:	learn: 0.1366454	total: 147ms	remaining: 982ms
130:	learn: 0.1360459	total: 148ms	remaining: 980ms
131:	learn: 0.1355395	total: 149ms	remaining: 978ms
132:	learn: 0.1348592	total: 150ms	remaining: 977ms
133:	learn: 0.1341834	total: 151ms	remaining: 975ms
134:	learn: 0.1337913	total: 152ms	remaining: 973ms
135:	learn: 0.1332693	total: 153ms	remaining: 971ms
136:	learn: 0.1327892	total: 154ms	remaining: 970ms
137:	learn: 0.1322904	total: 155ms	remaining: 968ms
138:	learn: 0.1318569	total: 156ms	remaining: 968ms
139:	learn: 0.1314219	total: 158ms	remaining: 968ms
140:	learn: 0.1305557	total: 159ms	remaining: 966ms
141:	learn: 0.1298950	total: 160ms	remaining: 965ms
142:	learn: 0.1294684	total: 161ms	remaining: 963ms
143:	learn: 0.1287264	total: 162ms	remaining: 962ms
144:	learn: 0.1282401	total: 163ms	remaining: 960ms
145:	learn: 0.1278251	total: 164ms	remaining: 958ms
146:	learn: 0.1271787	total: 165ms	remaining: 956ms
147:	learn: 0.1264364	total: 166ms	remaining: 953ms
148:	learn: 0.1258627	total: 167ms	remaining: 951ms
149:	learn: 0.1254454	total: 168ms	remaining: 950ms
150:	learn: 0.1247962	total: 169ms	remaining: 948ms
151:	learn: 0.1244207	total: 170ms	remaining: 947ms
152:	learn: 0.1238832	total: 171ms	remaining: 946ms
153:	learn: 0.1234354	total: 172ms	remaining: 947ms
154:	learn: 0.1229918	total: 173ms	remaining: 945ms
155:	learn: 0.1222974	total: 175ms	remaining: 944ms
156:	learn: 0.1218578	total: 175ms	remaining: 942ms
157:	learn: 0.1214165	total: 176ms	remaining: 940ms
158:	learn: 0.1210456	total: 178ms	remaining: 939ms
159:	learn: 0.1205652	total: 179ms	remaining: 938ms
160:	learn: 0.1199510	total: 180ms	remaining: 936ms
161:	learn: 0.1196028	total: 181ms	remaining: 934ms
162:	learn: 0.1189991	total: 182ms	remaining: 932ms
163:	learn: 0.1184664	total: 183ms	remaining: 931ms
164:	learn: 0.1180929	total: 184ms	remaining: 929ms
165:	learn: 0.1176238	total: 185ms	remaining: 927ms
166:	learn: 0.1169895	total: 186ms	remaining: 926ms
167:	learn: 0.1163313	total: 187ms	remaining: 925ms
168:	learn: 0.1158433	total: 188ms	remaining: 924ms
169:	learn: 0.1156609	total: 189ms	remaining: 923ms
170:	learn: 0.1152905	total: 190ms	remaining: 921ms
171:	learn: 0.1149141	total: 191ms	remaining: 919ms
172:	learn: 0.1143472	total: 192ms	remaining: 918ms
173:	learn: 0.1138186	total: 193ms	remaining: 916ms
174:	learn: 0.1133194	total: 194ms	remaining: 914ms
175:	learn: 0.1129820	total: 195ms	remaining: 913ms
176:	learn: 0.1125505	total: 196ms	remaining: 912ms
177:	learn: 0.1121469	total: 197ms	remaining: 911ms
178:	learn: 0.1113058	total: 198ms	remaining: 909ms
179:	learn: 0.1106499	total: 199ms	remaining: 907ms
180:	learn: 0.1103078	total: 200ms	remaining: 906ms
181:	learn: 0.1097771	total: 201ms	remaining: 904ms
182:	learn: 0.1091606	total: 202ms	remaining: 903ms
183:	learn: 0.1086579	total: 203ms	remaining: 902ms
184:	learn: 0.1080073	total: 204ms	remaining: 900ms
185:	learn: 0.1075701	total: 205ms	remaining: 899ms
186:	learn: 0.1070381	total: 206ms	remaining: 897ms
187:	learn: 0.1065363	total: 207ms	remaining: 896ms
188:	learn: 0.1060643	total: 208ms	remaining: 894ms
189:	learn: 0.1054650	total: 209ms	remaining: 893ms
190:	learn: 0.1048938	total: 211ms	remaining: 892ms
191:	learn: 0.1044339	total: 212ms	remaining: 891ms
192:	learn: 0.1038782	total: 213ms	remaining: 890ms
193:	learn: 0.1034434	total: 214ms	remaining: 889ms
194:	learn: 0.1030416	total: 215ms	remaining: 888ms
195:	learn: 0.1026738	total: 217ms	remaining: 890ms
196:	learn: 0.1021735	total: 218ms	remaining: 890ms
197:	learn: 0.1016602	total: 219ms	remaining: 888ms
198:	learn: 0.1014698	total: 220ms	remaining: 887ms
199:	learn: 0.1011503	total: 221ms	remaining: 885ms
200:	learn: 0.1009444	total: 222ms	remaining: 883ms
201:	learn: 0.1005053	total: 223ms	remaining: 882ms
202:	learn: 0.1001169	total: 224ms	remaining: 881ms
203:	learn: 0.0994163	total: 225ms	remaining: 879ms
204:	learn: 0.0990118	total: 226ms	remaining: 878ms
205:	learn: 0.0985773	total: 227ms	remaining: 876ms
206:	learn: 0.0980268	total: 228ms	remaining: 874ms
207:	learn: 0.0973965	total: 229ms	remaining: 873ms
208:	learn: 0.0968915	total: 230ms	remaining: 871ms
209:	learn: 0.0961772	total: 231ms	remaining: 869ms
210:	learn: 0.0955932	total: 232ms	remaining: 868ms
211:	learn: 0.0951501	total: 233ms	remaining: 867ms
212:	learn: 0.0946264	total: 234ms	remaining: 866ms
213:	learn: 0.0942111	total: 235ms	remaining: 864ms
214:	learn: 0.0938187	total: 236ms	remaining: 863ms
215:	learn: 0.0936418	total: 237ms	remaining: 862ms
216:	learn: 0.0931226	total: 238ms	remaining: 860ms
217:	learn: 0.0928040	total: 239ms	remaining: 858ms
218:	learn: 0.0924319	total: 240ms	remaining: 856ms
219:	learn: 0.0918626	total: 241ms	remaining: 855ms
220:	learn: 0.0914369	total: 242ms	remaining: 853ms
221:	learn: 0.0911791	total: 243ms	remaining: 852ms
222:	learn: 0.0909382	total: 244ms	remaining: 850ms
223:	learn: 0.0907843	total: 245ms	remaining: 849ms
224:	learn: 0.0903894	total: 246ms	remaining: 847ms
225:	learn: 0.0901048	total: 247ms	remaining: 846ms
226:	learn: 0.0896905	total: 248ms	remaining: 845ms
227:	learn: 0.0894007	total: 249ms	remaining: 844ms
228:	learn: 0.0892340	total: 250ms	remaining: 843ms
229:	learn: 0.0889104	total: 251ms	remaining: 841ms
230:	learn: 0.0886907	total: 252ms	remaining: 840ms
231:	learn: 0.0883434	total: 253ms	remaining: 839ms
232:	learn: 0.0879486	total: 254ms	remaining: 838ms
233:	learn: 0.0876839	total: 255ms	remaining: 836ms
234:	learn: 0.0873936	total: 256ms	remaining: 835ms
235:	learn: 0.0870297	total: 258ms	remaining: 834ms
236:	learn: 0.0866981	total: 258ms	remaining: 832ms
237:	learn: 0.0860933	total: 259ms	remaining: 830ms
238:	learn: 0.0857940	total: 260ms	remaining: 829ms
239:	learn: 0.0855349	total: 261ms	remaining: 828ms
240:	learn: 0.0851792	total: 262ms	remaining: 827ms
241:	learn: 0.0849574	total: 264ms	remaining: 826ms
242:	learn: 0.0846038	total: 265ms	remaining: 825ms
243:	learn: 0.0842624	total: 266ms	remaining: 823ms
244:	learn: 0.0839272	total: 267ms	remaining: 822ms
245:	learn: 0.0836038	total: 268ms	remaining: 820ms
246:	learn: 0.0831824	total: 269ms	remaining: 819ms
247:	learn: 0.0829290	total: 270ms	remaining: 818ms
248:	learn: 0.0824701	total: 271ms	remaining: 817ms
249:	learn: 0.0822909	total: 272ms	remaining: 815ms
250:	learn: 0.0818715	total: 273ms	remaining: 813ms
251:	learn: 0.0814071	total: 274ms	remaining: 812ms
252:	learn: 0.0810428	total: 275ms	remaining: 811ms
253:	learn: 0.0805835	total: 275ms	remaining: 809ms
254:	learn: 0.0803634	total: 276ms	remaining: 807ms
255:	learn: 0.0801219	total: 277ms	remaining: 806ms
256:	learn: 0.0798226	total: 278ms	remaining: 805ms
257:	learn: 0.0796555	total: 280ms	remaining: 804ms
258:	learn: 0.0791606	total: 281ms	remaining: 804ms
259:	learn: 0.0788152	total: 282ms	remaining: 802ms
260:	learn: 0.0782688	total: 283ms	remaining: 801ms
261:	learn: 0.0779555	total: 284ms	remaining: 799ms
262:	learn: 0.0776193	total: 285ms	remaining: 798ms
263:	learn: 0.0774989	total: 286ms	remaining: 797ms
264:	learn: 0.0773095	total: 287ms	remaining: 795ms
265:	learn: 0.0772195	total: 288ms	remaining: 794ms
266:	learn: 0.0768895	total: 289ms	remaining: 793ms
267:	learn: 0.0765614	total: 290ms	remaining: 792ms
268:	learn: 0.0762073	total: 291ms	remaining: 791ms
269:	learn: 0.0759786	total: 292ms	remaining: 789ms
270:	learn: 0.0756790	total: 293ms	remaining: 788ms
271:	learn: 0.0753355	total: 294ms	remaining: 787ms
272:	learn: 0.0750694	total: 295ms	remaining: 785ms
273:	learn: 0.0748010	total: 296ms	remaining: 784ms
274:	learn: 0.0744363	total: 297ms	remaining: 783ms
275:	learn: 0.0742160	total: 298ms	remaining: 782ms
276:	learn: 0.0738919	total: 299ms	remaining: 781ms
277:	learn: 0.0737301	total: 300ms	remaining: 779ms
278:	learn: 0.0734091	total: 301ms	remaining: 778ms
279:	learn: 0.0731243	total: 302ms	remaining: 776ms
280:	learn: 0.0730198	total: 303ms	remaining: 775ms
281:	learn: 0.0729386	total: 304ms	remaining: 774ms
282:	learn: 0.0728320	total: 305ms	remaining: 772ms
283:	learn: 0.0725513	total: 306ms	remaining: 771ms
284:	learn: 0.0723449	total: 307ms	remaining: 770ms
285:	learn: 0.0722559	total: 308ms	remaining: 769ms
286:	learn: 0.0719037	total: 309ms	remaining: 768ms
287:	learn: 0.0717020	total: 310ms	remaining: 767ms
288:	learn: 0.0716131	total: 311ms	remaining: 766ms
289:	learn: 0.0715387	total: 313ms	remaining: 766ms
290:	learn: 0.0714663	total: 314ms	remaining: 764ms
291:	learn: 0.0713177	total: 315ms	remaining: 763ms
292:	learn: 0.0712349	total: 316ms	remaining: 763ms
293:	learn: 0.0709170	total: 317ms	remaining: 762ms
294:	learn: 0.0706754	total: 319ms	remaining: 762ms
295:	learn: 0.0701311	total: 320ms	remaining: 760ms
296:	learn: 0.0699102	total: 321ms	remaining: 759ms
297:	learn: 0.0696289	total: 322ms	remaining: 758ms
298:	learn: 0.0694369	total: 323ms	remaining: 757ms
299:	learn: 0.0692121	total: 324ms	remaining: 756ms
300:	learn: 0.0688801	total: 325ms	remaining: 755ms
301:	learn: 0.0684884	total: 326ms	remaining: 754ms
302:	learn: 0.0682747	total: 327ms	remaining: 753ms
303:	learn: 0.0679512	total: 328ms	remaining: 752ms
304:	learn: 0.0677917	total: 329ms	remaining: 750ms
305:	learn: 0.0675872	total: 330ms	remaining: 749ms
306:	learn: 0.0673940	total: 331ms	remaining: 748ms
307:	learn: 0.0672122	total: 332ms	remaining: 746ms
308:	learn: 0.0669096	total: 333ms	remaining: 745ms
309:	learn: 0.0668557	total: 334ms	remaining: 744ms
310:	learn: 0.0666078	total: 335ms	remaining: 743ms
311:	learn: 0.0664028	total: 336ms	remaining: 741ms
312:	learn: 0.0662306	total: 337ms	remaining: 740ms
313:	learn: 0.0660588	total: 338ms	remaining: 739ms
314:	learn: 0.0658921	total: 340ms	remaining: 739ms
315:	learn: 0.0657409	total: 341ms	remaining: 739ms
316:	learn: 0.0655846	total: 342ms	remaining: 737ms
317:	learn: 0.0652172	total: 343ms	remaining: 736ms
318:	learn: 0.0649923	total: 344ms	remaining: 735ms
319:	learn: 0.0646847	total: 345ms	remaining: 734ms
320:	learn: 0.0643574	total: 346ms	remaining: 732ms
321:	learn: 0.0642986	total: 347ms	remaining: 731ms
322:	learn: 0.0641328	total: 348ms	remaining: 730ms
323:	learn: 0.0639340	total: 349ms	remaining: 729ms
324:	learn: 0.0636588	total: 350ms	remaining: 727ms
325:	learn: 0.0634876	total: 351ms	remaining: 726ms
326:	learn: 0.0632321	total: 352ms	remaining: 725ms
327:	learn: 0.0630039	total: 353ms	remaining: 723ms
328:	learn: 0.0627646	total: 354ms	remaining: 722ms
329:	learn: 0.0625186	total: 355ms	remaining: 721ms
330:	learn: 0.0623612	total: 356ms	remaining: 720ms
331:	learn: 0.0621818	total: 357ms	remaining: 719ms
332:	learn: 0.0620948	total: 358ms	remaining: 718ms
333:	learn: 0.0618695	total: 359ms	remaining: 716ms
334:	learn: 0.0615734	total: 360ms	remaining: 715ms
335:	learn: 0.0613817	total: 361ms	remaining: 714ms
336:	learn: 0.0612154	total: 362ms	remaining: 713ms
337:	learn: 0.0610645	total: 363ms	remaining: 711ms
338:	learn: 0.0609063	total: 364ms	remaining: 710ms
339:	learn: 0.0606126	total: 365ms	remaining: 709ms
340:	learn: 0.0604666	total: 366ms	remaining: 708ms
341:	learn: 0.0601550	total: 367ms	remaining: 706ms
342:	learn: 0.0599553	total: 368ms	remaining: 705ms
343:	learn: 0.0597425	total: 369ms	remaining: 704ms
344:	learn: 0.0594974	total: 370ms	remaining: 703ms
345:	learn: 0.0593546	total: 372ms	remaining: 703ms
346:	learn: 0.0590594	total: 373ms	remaining: 702ms
347:	learn: 0.0588181	total: 374ms	remaining: 701ms
348:	learn: 0.0586646	total: 375ms	remaining: 700ms
349:	learn: 0.0584867	total: 376ms	remaining: 698ms
350:	learn: 0.0582365	total: 377ms	remaining: 697ms
351:	learn: 0.0580864	total: 378ms	remaining: 696ms
352:	learn: 0.0577622	total: 379ms	remaining: 695ms
353:	learn: 0.0577089	total: 380ms	remaining: 693ms
354:	learn: 0.0576731	total: 381ms	remaining: 692ms
355:	learn: 0.0575018	total: 382ms	remaining: 691ms
356:	learn: 0.0573243	total: 383ms	remaining: 690ms
357:	learn: 0.0570670	total: 384ms	remaining: 689ms
358:	learn: 0.0568591	total: 385ms	remaining: 688ms
359:	learn: 0.0567222	total: 386ms	remaining: 687ms
360:	learn: 0.0566879	total: 387ms	remaining: 686ms
361:	learn: 0.0565820	total: 388ms	remaining: 684ms
362:	learn: 0.0564320	total: 390ms	remaining: 684ms
363:	learn: 0.0561363	total: 391ms	remaining: 683ms
364:	learn: 0.0559057	total: 392ms	remaining: 682ms
365:	learn: 0.0555721	total: 393ms	remaining: 681ms
366:	learn: 0.0553015	total: 394ms	remaining: 680ms
367:	learn: 0.0550399	total: 395ms	remaining: 678ms
368:	learn: 0.0548669	total: 396ms	remaining: 677ms
369:	learn: 0.0547167	total: 397ms	remaining: 676ms
370:	learn: 0.0546098	total: 398ms	remaining: 675ms
371:	learn: 0.0545810	total: 399ms	remaining: 674ms
372:	learn: 0.0545174	total: 400ms	remaining: 673ms
373:	learn: 0.0543556	total: 401ms	remaining: 672ms
374:	learn: 0.0541133	total: 403ms	remaining: 671ms
375:	learn: 0.0539062	total: 404ms	remaining: 670ms
376:	learn: 0.0538309	total: 405ms	remaining: 669ms
377:	learn: 0.0534689	total: 406ms	remaining: 667ms
378:	learn: 0.0533985	total: 407ms	remaining: 666ms

In [24]:
#saving the models

import pickle



filename = 'XGB_reg_basic.sav'
pickle.dump(XGB_reg_basic, open(filename, 'wb'))

filename = 'LGBM_reg_basic.sav'
pickle.dump(LGBM_reg_basic, open(filename, 'wb'))

filename = 'model_CB_basic.sav'
pickle.dump(model_CB_basic, open(filename, 'wb'))


filename = 'XGB_reg_all.sav'
pickle.dump(XGB_reg_all, open(filename, 'wb'))

filename = 'LGBM_reg_all.sav'
pickle.dump(LGBM_reg_all, open(filename, 'wb'))

filename = 'model_CB_all.sav'
pickle.dump(model_CB_all, open(filename, 'wb'))


filename = 'XGB_reg_all_plus_plus.sav'
pickle.dump(XGB_reg_all_plus_plus, open(filename, 'wb'))

filename = 'LGBM_reg_all_plus_plus.sav'
pickle.dump(LGBM_reg_all_plus_plus, open(filename, 'wb'))

filename = 'model_CB_all_plus_plus.sav'
pickle.dump(model_CB_all_plus_plus, open(filename, 'wb'))